### ISSUE TITLE
battle cruisers, cargo ships

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#1]
http://forum.game-icons.net/rpgs-cool-but-what-about-space-icons

**Comment by SomeRandomGameDev** [comment]
I'll try to make some. I'm in need of this kind of icons.

**Comment by Delapouite** [comment]
Spaceship: http://game-icons.net/delapouite/originals/spaceship.html
Starfighter: http://game-icons.net/delapouite/originals/starfighter.html
