### ISSUE TITLE
Any icon from this library importing all library

### ISSUE THREAD

**Issue by navid9696** [game-icons/icons#1013]
![image](https://github.com/game-icons/icons/assets/108413105/ca5a0ce3-a225-449d-8aec-18149afef499)
If Im importing icon in this way, it looks like its importing all library I guess, around 6.5MB maybe. I even try import on fresh project and its still the same

**Comment by Delapouite** [comment]
Hi. Sorry we don't offer support third party libraries. I guess you'll have to ask the author of `react-icons` directly to improve the tree-shaking experience during the bundling of your app.
