### ISSUE TITLE
staves and sticks

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#110]
Varlen
Creating an RPG with these icons but I'd love to see a few staves or sticks added to the icon selection. Thank you all for your hard work - I'm very impressed at the selection of icons. It seems to fit more needs than I ever expected! Here's a few examples to help the idea:

http://img02.deviantart.net/6d4c/i/2015/280/d/a/staff_adopts_35__closed__by_rittik_designs-d8d6mgq.jpg

http://img14.deviantart.net/b3ca/i/2012/090/6/7/magic_staffs_by_ladyowl-d4uhs59.jpg

http://vignette2.wikia.nocookie.net/runescape2/images/e/e9/Crystal_staff_detail.png/revision/latest?cb=20140922210324

http://orig08.deviantart.net/bddb/f/2008/347/8/4/magic_staff_by_raularosemena.jpg

**Comment by varlenthegray** [comment]
Tagging this (Hello, I'm Varlen)

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/magic-trident.html

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/skull-staff.html

**Comment by Delapouite** [comment]
Sheperd's crook http://game-icons.net/generalace135/originals/shepherds-crook.html

**Comment by Delapouite** [comment]
https://game-icons.net/1x1/delapouite/crescent-staff.html

Closing this issue as it's an infinite quest.
