### ISSUE TITLE
zombie

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#12]
http://forum.game-icons.net/zombie-icons

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/half-body-crawling.html

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/shambling-zombie.html

**Comment by Delapouite** [comment]
http://game-icons.net/movingalt/originals/raise-zombie.html

**Comment by gameiconthrowaway** [comment]
These zombie icons are so good. The raise-zombie link should be http://game-icons.net/skoll/originals/raise-zombie.html?
