### ISSUE TITLE
Spy logos

### ISSUE THREAD

**Issue by Bowsernight** [game-icons/icons#126]
We are doing a spy game and we couldn't really find a spy logo. Any spy related things would help us for sure and lots of people as well.

**Comment by Delapouite** [comment]
Sure! Spies are essential. Thanks for your suggestion.

**Comment by Delapouite** [comment]
https://github.com/game-icons/icons/issues/58

**Comment by Delapouite** [comment]
A first spy icon is ready. More will follow. http://game-icons.net/delapouite/originals/robber-mask.html

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/spy.html
