### ISSUE TITLE
Bug - Inkscape 0.91 - Rolling Dice

### ISSUE THREAD

**Issue by irongamer** [game-icons/icons#131]
The rolling dice svg in Inkscape 0.91 comes in with only two and a half sides on the upper die.  I've tried a number of different backgrounds and also tried breaking up the groups.  No dice... yeah.

http://game-icons.net/delapouite/originals/rolling-dices.html

![dice_bug](https://cloud.githubusercontent.com/assets/844598/13612103/9691a2b2-e51a-11e5-8bde-f2b1dfd2d24b.png)

**Comment by Delapouite** [comment]
The problem has been identified : negative number in paths should be prefixed with a space. I still need to find if it's a inkscape or a spec bug.

**Comment by Delapouite** [comment]
Here it is : https://bugs.launchpad.net/inkscape/+bug/1284409

Should be fixed when inkscape 0.92 is out
