### ISSUE TITLE
Barracks

### ISSUE THREAD

**Issue by Suppee** [game-icons/icons#132]
Historical or fantasy setting barracks preferably with a weapon icon on top such as a sword or an axe

**Comment by Delapouite** [comment]
Absolutely. AO2 barracks for ref : http://ageofempires.wikia.com/wiki/Barracks_%28Age_of_Empires_II%29

**Comment by Delapouite** [comment]
Here are modern barracks 

http://game-icons.net/delapouite/originals/barracks-tent.html
http://game-icons.net/delapouite/originals/barracks.html
http://game-icons.net/delapouite/originals/military-fort.html

**Comment by SuperKamiChazz** [comment]
Hoping for more fantasy themed barracks for goblins and orcs?

**Comment by Delapouite** [comment]
Here comes medial barracks https://game-icons.net/1x1/delapouite/medieval-barracks.html
