### ISSUE TITLE
TV remote control icon request

### ISSUE THREAD

**Issue by neilmunday** [game-icons/icons#134]
Hi,

Your icon repository and web site is a brilliant resource.

Would it be possible to get a TV remote control icon added please?

Many thanks,

Neil.

**Comment by Delapouite** [comment]
Hi Neil.

The TV remote is finally ready http://game-icons.net/delapouite/originals/tv-remote.html

**Comment by neilmunday** [comment]
Many thanks @Delapouite - it will come in handy for PES 2.1 (http://pes.mundayweb.com) !
