### ISSUE TITLE
Request integration in Fontello ?

### ISSUE THREAD

**Issue by rastapopougros** [game-icons/icons#140]
Fontello is open source and there is a process to integrate new icon sets.
http://fontello.com/

Here is the help :
https://github.com/fontello/fontello/wiki/How-to-suggest-font-to-fontello

**Comment by Delapouite** [comment]
Thanks, I'll have a look!

In the meantime, a font is already available : http://seiyria.com/gameicons-font/

**Comment by seiyria** [comment]
I'd be happy to help with integrating this into fontello, but there are a _lot_ of icons to tag manually, etc, so it'd have to be a group effort, I think!

**Comment by rastapopougros** [comment]
abandoned idea? :)

**Comment by InkyQuill** [comment]
I made a webfont with 3253 icons (seems too much for web, but still). There is an SVG file that can be used to upload to fontello. I hope this will be a good starting point for those who wants to pick icons for their own webfonts.

[https://files.inkyquill.net/fontello-game-icons.zip](https://files.inkyquill.net/fontello-game-icons.zip)
