### ISSUE TITLE
Directions (east, north, ...)

### ISSUE THREAD

**Issue by Evolena** [game-icons/icons#145]
Hello,

There is already a compass icon, but what about icons for directions: east, north, south and west?
Subdirections (north-est, ...) may be useful also for moving in diagonal, or some hexagonal directions...

Thanks a lot for your work!

**Comment by salattu** [comment]
I submitted a [pull request](https://github.com/game-icons/icons/pull/239) to address this, hope it's what you were looking for :)

**Comment by Evolena** [comment]
Yes, thank you.
However, the directions with letters fit for English, but not for all languages. But as it's SVG and I only would have to transform the W into a O, it should be manageable. And if I can't find how to do that, the first two generic icons are just perfect!
