### ISSUE TITLE
Camel

### ISSUE THREAD

**Issue by curtmack** [game-icons/icons#146]
There's already an elephant, a horse, a dog, a cat, and a rabbit - we just need a camel before we can make a complete [Arimaa](https://en.wikipedia.org/wiki/Arimaa) set.

**Comment by Delapouite** [comment]
Thanks! It's the second time it's requested so it's definitely going on top of the priority list.

https://github.com/game-icons/icons/issues/19

**Comment by gameiconthrowaway** [comment]
It looks really good.
