### ISSUE TITLE
spiky pit overlap issue

### ISSUE THREAD

**Issue by DreadKnight** [game-icons/icons#147]
This icon is kinda problematic, it should be edited and have spikes not overlap each others, or show the missing parts from the ones that are in the middle http://game-icons.net/delapouite/originals/spiky-pit.html

**Comment by Delapouite** [comment]
Yes you're right, I'm not really proud of this one. Alignments of the rows in the back would deserve better adjustement. I should create a "redo" list to add the icons who need adjustements.

**Comment by DreadKnight** [comment]
This still looks awful. I was hoping it would have been fixed by now, as I might need it :P
