### ISSUE TITLE
Community-Sourced Keywords

### ISSUE THREAD

**Issue by Deozaan** [game-icons/icons#150]
Some icons are hard to locate due to the somewhat arbitrary and limited categorization using tags.

It would be nice if anybody could add keywords to assist in searches, describing the icon.

For example, right now I am looking for but can't find this icon with circular arrows and a question mark: 
![game icons question](https://cloud.githubusercontent.com/assets/227734/14550805/1c9c610e-0289-11e6-94a1-9180248acf32.png)

I can't find it in "Arrow & Spear" and I don't see it in "Symbol" or "GUI" which have similar styled arrow icons and an icon containing a question mark. I can't find it anywhere except as included in the full preview sheet.

But if people could add keywords to help with searching, such as "question mark" and "arrows" or "circular" then that would help increase searchability for the files which are kind of abstract and hard to categorize into certain tags.

And no, I couldn't find the icon in the "Abstract" tag, either.

**Comment by Delapouite** [comment]
Hi

Here it is : http://game-icons.net/lorc/originals/uncertainty.html

You're perfectly right, this icon was hard to find. I've added the tags you suggest.
Opening the folksonomy would be great to improve the searchability of the website.

Right now, pages are static so it's technically impossible but I'll work on a solution.

Also the big cheatsheet could have the name of the icons written on it.

In the meantime don't hesitate to use this tracker to add suggestions.

**Comment by Deozaan** [comment]
Thank you very much!
