### ISSUE TITLE
Request - RPG CLass icons

### ISSUE THREAD

**Issue by PalaNolho** [game-icons/icons#168]
Hi,

I was just checking the game-icons website and this is amazing!!! :D

I was wondering if someone was thinking about doing some RPG "class" icons

IS anyone up to make some RPG class icons (ex: based on D&D classes)
I'm thinking about D&D classes but anyone can easily come up with new classes

some examples:
- Barbarian
- Bard
- Cleric
- Druid
- Fighter
- Monk
- Paladin
- Ranger
- Rogue
- Sorcerer
- Warlock
- Wizard

Many thanks

- Miguel Pinto

Note: I tried to add the "request" label, but was not able to find how :(

**Comment by Delapouite** [comment]
https://github.com/game-icons/icons/issues/148
