### ISSUE TITLE
sarcophagus

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#176]

**Comment by gameiconthrowaway** [comment]
A coffin is here http://game-icons.net/lorc/originals/coffin.html. Perhaps the coffin isn't sufficient if you want something like https://en.wikipedia.org/wiki/Sarcophagus#/media/File:Egypt.KV8.01.jpg?

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/sarcophagus.html
