### ISSUE TITLE
site features

### ISSUE THREAD

**Issue by skoll99** [game-icons/icons#186]
Hello!

Got some ideas for the site:
- Show number of downloads on each individual icon
- Show top list on the first page, maybe rank the most downloaded today/this week/year/ever?
- The popular icons on the first page have been the same for a while now. Maybe do random icons instead, so you can get inspiration even though you visited before?

Cheers

Skoll

**Comment by Delapouite** [comment]
Icons on the front page have been more randomised. Also new colorschemes have been added.

**Comment by skoll99** [comment]
Looks great!
