### ISSUE TITLE
Foreground color issue

### ISSUE THREAD

**Issue by Evolena** [game-icons/icons#196]
The foreground color doesn't work for the [gamepad icon on the site](http://game-icons.net/delapouite/originals/gamepad.html).
I suspect the `<g>` tag gets the color while the `<path>` still has its `fill="#fff"`.

Maybe some other icons are concerned.

**Comment by Delapouite** [comment]
Should be fixed. Thanks for detecting this.

**Comment by Evolena** [comment]
It's ok now, thanks. And I confirm I have found no other icon with this issue.
