### ISSUE TITLE
Bear

### ISSUE THREAD

**Issue by Muffty** [game-icons/icons#199]
There are lots of animals, but no bear.

**Comment by Delapouite** [comment]
You're right! We have a panda but no bear. I fuse this demand with the previous one: https://github.com/game-icons/icons/issues/88

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/bear-head.html

**Comment by Delapouite** [comment]
http://game-icons.net/cathelineau/originals/polar-bear.html
