### ISSUE TITLE
Is there a spreadsheet or database file with Icon-to-tags mapping?

### ISSUE THREAD

**Issue by luissncs** [game-icons/icons#203]
Hello! Is there a spreadsheet or database file which maps the icons with their corresponding tags as they appear on the website? For example "Zeppelin" has "vehicle" and "steampunk" as it's tags. This would very helpful. Thanks!

**Comment by Delapouite** [comment]
Hello.
No there's no such document yet. The current website is statically generated. Meanwhile, the search engine on the top right corner is pretty good to find icons, and I try to improve the quality of search results weekly.
