### ISSUE TITLE
Okay-Icon (opposite of Cancel-Icon)

### ISSUE THREAD

**Issue by teveshszat** [game-icons/icons#204]
It would be nice, if you add an "okay" icon to your collection.
A checkmark would be nice!

Usage: Okay-Button for dialogs.

(Opposite for http://game-icons.net/sbed/originals/cancel.html )

**Comment by SomeRandomGameDev** [comment]
The produced "Okay Icon" has been saved with all the Inkscape meta-stuff. As I've messed up with my branches, the Okay icon is in all my pull requests ...
Stripping it from Inkscape to Raw shall be done afterwards.

**Comment by teveshszat** [comment]
Thanks! :)
