### ISSUE TITLE
Make a Gitter Room

### ISSUE THREAD

**Issue by SomeRandomGameDev** [game-icons/icons#212]
Create a room under http://gitter.im so that we can interact more easily and share tips.

**Comment by Delapouite** [comment]
I can open a gitter room if you want, but I personally wont use it. It's bit too time consuming.

**Comment by SomeRandomGameDev** [comment]
It depends on active members. I see it as an IRC chan to improve reactivity and share tips and guidelines.

**Comment by Delapouite** [comment]
Here it is : https://gitter.im/game-icons/icons

I leave this issue open until I had a link from the README

**Comment by SomeRandomGameDev** [comment]
You should add a link in the contribution file in order to promote it, else, nobody will come on it.

**Comment by Delapouite** [comment]
You're right.

Done: https://github.com/game-icons/icons/commit/a9dcc88b9684aa6a17dfbd8ad0ce4dd67b2b2462
