### ISSUE TITLE
Steam icons

### ISSUE THREAD

**Issue by jeremyputeaux** [game-icons/icons#217]
Hello,

I'm looking for steam icons and I can't find any.
You know, something that is steaming before burning.

What do you think ?

**Comment by Delapouite** [comment]
Would a steaming kettle do the job?

**Comment by jeremyputeaux** [comment]
Hmm it could do the job, as long as we don't see the kettle.

**Comment by Delapouite** [comment]
https://twitter.com/EuroGamerGirl/status/792133414040154113

**Comment by Delapouite** [comment]
A small steam cloud has been added : http://game-icons.net/delapouite/originals/steam.html

**Comment by Delapouite** [comment]
More smoke : http://game-icons.net/lorc/originals/smoking-orb.html
