### ISSUE TITLE
Swap foreground and background color

### ISSUE THREAD

**Issue by Annegrim** [game-icons/icons#219]
Hello, hope this is the right place for game-icons.net suggestions (and i did search for this issue, but i might have missed something - im new to this)

## Request
I would like to have the ability to swap the foreground and the background color in the color picker box called "Colors".

Besides that the site (and the project) is really great, it really motivates me to make a game that is visally attractive, big shoutout to everyone involved.

**Comment by Delapouite** [comment]
Hi @Annegrim, a new swap colors button has been added. Thanks for the suggestion.
