### ISSUE TITLE
Farmer from Pikeman

### ISSUE THREAD

**Issue by Dude211212** [game-icons/icons#225]
Hello! 
I was working on a personal project and needed a farmer icon. So, with a quick copy paste or two, I made one from your pikeman icon- I think it would be a great addition to the farm set! The uploaded image isn't so great, but you can see the simple alterations made. 
![image](https://cloud.githubusercontent.com/assets/21113308/17793891/cd877b96-6578-11e6-93f6-3b8fd93f325e.png)

**Comment by Delapouite** [comment]
Nice idea @Dude211212 ! I've included it as a proper SVG : http://game-icons.net/delapouite/originals/farmer.html
Thanks again!
