### ISSUE TITLE
2 handed sword?

### ISSUE THREAD

**Issue by crazybyzantine** [game-icons/icons#232]
Existing choices for daggers, shortswords, longswords are great.
For the 5'-6' long European style, trying to mashup but someone with better talent might be able to do better.

Great site & resources for my homebrew board games!

**Comment by Delapouite** [comment]
Hi. Thanks!

Could your provide an image as reference?

**Comment by crazybyzantine** [comment]
Here's one, though this might be a little too elaborate for a minimalist icon: http://www.coldsteel-uk.com/store/two-handed-great-sword-88wgs-full-1.jpg
Otherwise similar to existing sword icons, just with longer hilt, thinner guards, longer/thinner blade.
-james

**Comment by Delapouite** [comment]
Here comes a two handed sword http://game-icons.net/delapouite/originals/two-handed-sword.html
