### ISSUE TITLE
All Alphabets

### ISSUE THREAD

**Issue by vishal3011** [game-icons/icons#233]
Some user might try to put just the alphabet as the icon for his/her application.
Adding them would be great.

**Comment by Delapouite** [comment]
Hi Vishal.
Well, that's what normal letters are for, aren't they?
This way the application designer has full control over the font, size, weight…

I'm sorry but your suggestion is too far away from the purpose of our collection of icons. It's intended to provide unusual shapes and drawings, not graphics that common.
