### ISSUE TITLE
medusa's head?

### ISSUE THREAD

**Issue by crazybyzantine** [game-icons/icons#235]
Greek collection has Hydra and a few other mythological items.
Looking for the classic Gorgon's Head like from Clash of the Titans.
I kitbashed a crude one from the Snake and Smitten icons but a true vector one would be better.

Man, I love this site!

**Comment by Delapouite** [comment]
Yes I had a Medusa head in mind during the roman/greek update a few weeks ago, it will be a welcome addition in the future.

**Comment by Cathelineau** [comment]
Well I just did one ! I will suggest it in my next mail for you, Delapouite.

**Comment by gameiconthrowaway** [comment]
+1

**Comment by Delapouite** [comment]
Medusa head and snakes http://game-icons.net/cathelineau/originals/medusa-head.html

**Comment by gameiconthrowaway** [comment]
Thank you so much!
