### ISSUE TITLE
52 card deck

### ISSUE THREAD

**Issue by aussiesim** [game-icons/icons#238]
I'd like to contribute a set of 52 card deck icons for something I'm working on but would like some feedback before I commit to creating all 52.

So, first question: is there any interest in such a thing?
Secondly: should it look more "dice-like" (like poker dice), "card-like" or simpler for easier readability?
![king-of-clubs-dice-like](https://cloud.githubusercontent.com/assets/22422645/18826464/db5be1b0-8410-11e6-85fe-38218d8f2bad.png) ![king-of-clubs-card-like](https://cloud.githubusercontent.com/assets/22422645/18826478/eb445b66-8410-11e6-9a79-9feb41ebd16a.png) ![king-of-clubs-simple](https://cloud.githubusercontent.com/assets/22422645/18826485/f23629d6-8410-11e6-9a8e-a80d89fdfecf.png)

I've used Lorc's suits icon (http://game-icons.net/lorc/originals/suits.html) for the suits and if we go with dice I'd use Delapouite's dice (http://game-icons.net/delapouite/dice/dice-six-faces-three.html) as the template for style consistency.

(I'm sure there would be a programmatic way of automating the process but I figure that by the time I figure out the structure of an SVG file and how to do it properly then I'll be better off just doing it manually.)

**Comment by FluffyXVI** [comment]
I like the card style, the dice looks a little bit too cramped in my opinion.

**Comment by Delapouite** [comment]
Hi @aussiesim thanks for this proposal!

I think I prefer the one in the middle but I'm afraid it won't scale very well for the number 10 card.
Could you post a test of how it would look for this specific card?

**Comment by salattu** [comment]
Delapouite is right about the number 10 - as is, a 10 would have to be smaller in size than other numbers. They should all be of a size. I like the dice-like icon myself - it affords the most space - but would suggest reducing the size of the letter/number by about a third and using a serif font for enhanced readability.

**Comment by aussiesim** [comment]
Cool! Thanks for the feedback guys! Will post some options taking your suggestions into consideration as soon as I can.

In the mean time, I had an idea on the way home from work about going a bit off-script... thoughts?

![10clubs](https://cloud.githubusercontent.com/assets/22422645/18952345/97653db6-868c-11e6-91f5-4e02c87655eb.png) ![10-diamonds](https://cloud.githubusercontent.com/assets/22422645/18952346/9767b258-868c-11e6-86d4-c43b9be032c8.png) ![10-hearts](https://cloud.githubusercontent.com/assets/22422645/18952347/9769b49a-868c-11e6-8464-59e4999b250a.png) ![10-spades](https://cloud.githubusercontent.com/assets/22422645/18952348/976dcce2-868c-11e6-8cd3-adf2116e0811.png)
I'm open to experimentation. In my head, I imagined just using a stroke around the font but in practice it didn't look right. Maybe I should stroke it and fill in the holes as a solid backdrop for the text in front of the suit symbol? I think this muddies the text / suit too much though.
![10-clubs-stroked](https://cloud.githubusercontent.com/assets/22422645/18952912/43a3f9d0-868f-11e6-83d4-7fd909dcb47c.png)

As an aside,  I seem to be getting a weird thing in Inkscape where it's not rendering the fonts correctly, like it's substituting one font for another. It's most obvious with the wingding fonts (not that I intend to use them, just an example) - they are appearing as normal text. If anyone has encountered such a thing I'd love to hear about it.

**Comment by aussiesim** [comment]
10 card. Others will have to wait, sorry.
![10-clubs-card](https://cloud.githubusercontent.com/assets/22422645/18953168/6739108c-8690-11e6-8e93-ad97d8bebf54.png)

**Comment by aussiesim** [comment]
This is getting closer to my "driving-home-from-work" idea...
![another-try](https://cloud.githubusercontent.com/assets/22422645/19020527/48d1863c-88ee-11e6-90a2-3766cdff4646.png)

**Comment by aussiesim** [comment]
Alright, so I've got this bit out of my system. Any feedback is appreciated. Let me know if you'd like me to submit the svg files. I'll work on cards and dice next. Cheers!

![52-card-deck-values](https://cloud.githubusercontent.com/assets/22422645/19030431/1474c9d2-8991-11e6-9433-4aa8c9b0b8dd.png)

**Comment by salattu** [comment]
Nifty! I just had a thought for your next iteration on the cards and dice: the bottom right suit symbol is typically inverted in playing cards. In your previous samples you had the top left and bottom right both oriented upwards.

Really like the look of the 10 card!

**Comment by aussiesim** [comment]
*slaps forehead*

Of course! I will correct the orientation for the next lot.

Some of the poker dice that I've seen have the suit in all four corners. Does anyone else think that's overkill?

**Comment by salattu** [comment]
It is absolutely overkill to have the suit in all corners. Two opposing corners looks right because we're used to seeing that with playing cards, but you really only need one. With physical cards, players will be looking at them from opposite directions, so it makes sense to provide visual cues in different orientations. 

Have you thought of opposing colors for suit and numbers, like this?

![g4185](https://cloud.githubusercontent.com/assets/18619671/19039696/a65fa004-8989-11e6-99d6-743924a15127.png)

**Comment by aussiesim** [comment]
This. This is what I love about working collaboratively. Thanks Salattu, I love it! I'll have a play around with it.

**Comment by aussiesim** [comment]
I think that, in keeping with the style of the other icons on the site, there needs to be an invisible border around the icon. May I present the minimalist 52 card values...
![52-card-values-minimalist](https://cloud.githubusercontent.com/assets/22422645/19072744/3aa6fe9c-8a7a-11e6-98a5-87eea185331a.png)

Also, would appreciate any feedback on the font used for the card-style set:
![52-card-deck-values-cards](https://cloud.githubusercontent.com/assets/22422645/19072765/59454340-8a7a-11e6-82a6-1b44942bc405.png)

**Comment by aussiesim** [comment]
Yoops... I see what I did there. I'll fix that tonight. Thanks!

**Comment by aussiesim** [comment]
Alright, fixed it. Now working through saving each individual card.
=)
![minimalist-10s](https://cloud.githubusercontent.com/assets/22422645/19112917/bcb51b8c-8b4a-11e6-9c5d-f5c5926be14b.png)

**Comment by FluffyXVI** [comment]
I love the card style ones you have done.

**Comment by Delapouite** [comment]
Great job!

We should pay attention about the number of nodes resulting of the use of serif-fonts in the secoon example. For example the letter Q for queens may have a lots of them that we need to optimize correctly during export.

**Comment by aussiesim** [comment]
Thanks guys! Time is not my friend at the moment but I have emailed Delapouite with the card files. I think the number of nodes created by the serif-font should hopefully be acceptable but let me know if there is still work to be done.

**Comment by Delapouite** [comment]
It's online. Thanks to everyone involved! http://game-icons.net/tags/board.html

I close this thread to keep track that is has been published but don't hesitate to go along with the conversation.

**Comment by FluffyXVI** [comment]
Only one of the cards is showing up in the recent additions list. Is this intentional?

**Comment by Delapouite** [comment]
Yes, if 52 similar cards were displayed in this page it will be a bit overwhelming.

**Comment by aussiesim** [comment]
Ha! Yeah, I definitely don't deserve that much limelight.  =D

**Comment by Delapouite** [comment]
Also the release was announced yesterday on twitter https://twitter.com/GameIcons/status/786258512280186880

**Comment by FluffyXVI** [comment]
Ah yep, I didn't see the twitter announcement
