### ISSUE TITLE
autobus

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#240]

**Comment by aussiesim** [comment]
Please excuse my ignorance... I had to Google "autobus" and came up with two possible meanings, both pretty equally weighted - either a group of cyclists or a particular type of bus. Which one do you mean?

**Comment by salattu** [comment]
Assuming it's the bus as a type of public transportation, I'll pick this up. Was just thinking to start work on an icon set of various means of transportation :)

**Comment by salattu** [comment]
So how's this for a start? I struggled to give the bus any character. Ideas? Requests?

![bus front](https://cloud.githubusercontent.com/assets/18619671/19620658/bad60ca2-988a-11e6-8ef6-851fcb185cfa.png)
![bus side](https://cloud.githubusercontent.com/assets/18619671/19620659/bad8ac5a-988a-11e6-9abd-aa7a5f740bbe.png)
![tram 3d](https://cloud.githubusercontent.com/assets/18619671/19620660/badc0206-988a-11e6-80bf-5cb7a179065d.png)
![tram uhh old i guess](https://cloud.githubusercontent.com/assets/18619671/19620657/bad25a80-988a-11e6-8d67-294b8b3bac8b.png)
![tram front](https://cloud.githubusercontent.com/assets/18619671/19620661/bade5bdc-988a-11e6-9b12-f9914c331cfc.png)
![tram side](https://cloud.githubusercontent.com/assets/18619671/19620662/bae21592-988a-11e6-8d44-a37eca3af8aa.png)

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/bus.html
