### ISSUE TITLE
New version of Studio

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#246]
Hello all.

What I call the _studio_ is the set of tools that appears in the left colum on each icon page ; this is the place where you can tweak lots of things like colors, sizes…

Today a new version of the studio has been released, totally rewritten from the ground up.

New options have been added:
- new shapes (horizontal hexagon, octagon, star)
- glow effect on foreground
- optional clipping of foreground
- independent text color
- text size
- more presets

Many things can still be improved / added. 

Here are a few I have in mind:
- more than 1 text
- live dragging for text instead of setting the x/y coordinates
- choose text stroke background

Feel free to add your suggestions in this thread if you have any feedback or ideas. Thanks!

**Comment by sweil9** [comment]
Please can you add the transparent background option back ? It's really the only one i used in my project, thanks.

**Comment by sweil9** [comment]
Ah there is a way to do that, nevermind ty :P

**Comment by Delapouite** [comment]
Hi.

Yes it's a bit different now. The new color picker is more powerful than the previous one.
You can select the alpha of each color. So if you set the alpha to 0 for the background color, you get the previous behavior.

**Comment by VorpalPapercut** [comment]
Looks good!  However, PNG icons are now downloading at size 512 regardless of the size picked.  (SVG, however, now pays attention to size picked.)

**Comment by Delapouite** [comment]
Good catch @VorpalPapercut. Thanks! It should be fixed now.

**Comment by FluffyXVI** [comment]
Thankyou so much for the colour palette! It makes things so much easier, especially choosing white.

**Comment by Delapouite** [comment]
Yes, the new color palettes are indeed quite cool and a true improvement over the previous version.

We have to thank the tremendous work of those people : http://casesandberg.github.io/react-color/

**Comment by salattu** [comment]
Superb! The studio is now very powerful - I see a future parallel site for people to post their designs made with just the studio.

One thing comes to mind: a toggle for a serif font would help increase readability in small icons.

**Comment by Delapouite** [comment]
Yes, a user creation gallery would be great. But it's currently impossible to implement it since the site is not dynamically generated.

Meanwhile, I've just added a dropdown to select between `serif / sans` for the text (you may need to F5 the page to get it).

It's difficult to add more fonts because it depends of the platform (windows, mac, linux…). I'll see later to maybe introduce async loading of web-fonts.

Also, an accordion has been added. This studio is starting to get quite crowded, and this way, I'll be able to put more stuff in each section soon.

**Comment by VorpalPapercut** [comment]
@Delapouite, it was definitely working earlier, but looks like your additional changes have unfixed the PNG size issue.  =P

**Comment by VorpalPapercut** [comment]
And already it is fixed.  My hat is off to you, sir.

**Comment by Delapouite** [comment]
A new update is ready:

- more background shapes (star5, rhombus…)
- more control over the foreground shadow (blur, x/y, in/out, color)
- better preset dropdown
- link to help

**Comment by ryanabrams** [comment]
I'd love the ability to move the icon around within the background shape.

For example, shrinking it, then moving it upwards so there's room for text below, etc.

**Comment by ishmadrad** [comment]
Probably I can't find it, however I can't export the icon (SVG or PNG) with NO background at all. Ie. I want to obtain the simple icon with a transparent background. I really can't figure out how to obtain it.
Thanks in advance for the info.

**Comment by Delapouite** [comment]
Thanks for you feedback @ishmadrad .

I've added a section in the help page http://game-icons.net/studio.html explaining what RGBA means.

**Comment by Delapouite** [comment]
New big update for the studio! Be sure to clean your cache (CTRL+F5) to get it.

You can now style each sub-paths of the foreground individually. Click on the *Break Apart* button in the *Foreground* section to let the magic happen.
![break-apart](https://cloud.githubusercontent.com/assets/39315/23657846/57d0973c-0340-11e7-85c4-f049ecf01eb1.png)

Here are the examples of what can now be achieved:

![yolo](https://cloud.githubusercontent.com/assets/39315/23657855/6733be98-0340-11e7-8cc2-def4478161fc.png)

**Comment by perlDreamer** [comment]
I'd like to suggest that you open source this so we can help you work on it, fixing bugs and adding new features.

**Comment by Delapouite** [comment]
I'd love the ability to move the icon around within the background shape.

    For example, shrinking it, then moving it upwards so there's room for text below, etc.
@ryanabrams 

-> You can now drag the foreground shape with your mouse. Make sure to hard refresh the page (CTRL+F5) to get this feature.

**Comment by parduz** [comment]
Many thanks for this!!!

What i'd like to ask for is:
- new background shapes like various shields, flags/banners, and anything else you could use to make "araldic symbols" with the icons
- Ability to pick an icon as a background shape (maybe just the ones that will have a new tag "vaild background")
- the ability to "pick" more than one icon, edit them as a whole in the studio (so i can see, for example, what stroke width is good for all of them), and download all of them.

As a programmer (in a different field) i see that i'm aking hard things.

Thanks again for this invualuable resource

**Comment by JR-Utily** [comment]
I agree with the `All parameters as a string of text to be copied (and saved by user in a text file) and pasted in the future to get the same setting used in the past`
To serialize the configuration and to make it available again would be awesome.
I'm doing different sets of icons, which some should be consistent between them, and some should not. I'm currently writing all config to apply (like RGB colors and so on) on a text file in the project to be able to switch from one context to another one.

**Comment by snappedToGrid** [comment]
Here's a quick example of how I pixelated this icon using the displacement map:

https://game-icons.net/1x1/delapouite/boat-propeller.html

![image](https://user-images.githubusercontent.com/94614297/154269713-80bf9604-a379-4fac-a741-597a65840dec.png)

**Comment by DragonSlayr15001** [comment]
i think it should be possible to delete unwanted paths after splitting them

**Comment by marcusmattingly** [comment]
Love this thing! So useful.

BUG: If you reposition the foreground at all then the clipping doesn't work correctly. I wanted to reposition a dagger so you see the hilt and part of the blade and then clip the rest to a circle background. Could not get it to work. Clip works fine as long as you don't move the foreground.

**Comment by nanoscotish** [comment]
hi, would it possible to upload a icon to web?

**Comment by Aaron-triplett-Work** [comment]
Is it at all possible to layer some of these icons on top of each other either as separate layers or if easier using the second layer as a badge. 
not sure how hard this is to do for the back end, you can do it in GIMP as a current solution if anyone else needs this resolve but was asking if there is an in house ability for this?

**Comment by Shieke** [comment]
Hello, hi! Would it be possible to add an option to save and import kind of a "User-made" preset to the studio? So if I had an icon set that I was working on with a circle background and frame, I could save it for later so that if I had to do other icon sets, it would be easy to come back to that one later? Not sure if that's possible with how the site's built, but it's an idea!

**Comment by NicholasDewberryOfficial** [comment]
> Hello, hi! Would it be possible to add an option to save and import kind of a "User-made" preset to the studio? So if I had an icon set that I was working on with a circle background and frame, I could save it for later so that if I had to do other icon sets, it would be easy to come back to that one later? Not sure if that's possible with how the site's built, but it's an idea!

I was just thinking that, and made an issue at: https://github.com/game-icons/icons/issues/1059

I can't seem to find the code for the studio itself online

**Comment by Eepsquared** [comment]
Still no way to change font?
