### ISSUE TITLE
Canned food

### ISSUE THREAD

**Issue by Ojanco** [game-icons/icons#248]
It would be nice an icon with one or more cans of canned food. (I'm Heavenly Dog, after all this time, I made this account in order to continue contributing ideas).

**Comment by Delapouite** [comment]
Good idea. Welcome back Heavenly Dog!

**Comment by Ojanco** [comment]
Ty man! :)

**Comment by Delapouite** [comment]
Opened food can : http://game-icons.net/delapouite/originals/opened-food-can.html
