### ISSUE TITLE
Eating and Drinking

### ISSUE THREAD

**Issue by Muffty** [game-icons/icons#251]
Hi,

what about a "Eating" and "Drinking" icon?

Cheers,
Muffty

**Comment by Delapouite** [comment]
Nice suggestion, thanks.

Here they are : http://game-icons.net/delapouite/originals/drinking.html
http://game-icons.net/delapouite/originals/eating.html

**Comment by graspee** [comment]
They are too similar. The point of icons is to be unique and clearly recognisable and distinguishable from each other. I would suggest the tilted glass of water on its own, and for the food, a traditional roast turkey with a few slices already carved off.

**Comment by Evolena** [comment]
These already nearly exist:

http://game-icons.net/lorc/originals/chicken-leg.html
http://game-icons.net/lorc/originals/wine-glass.html
http://game-icons.net/delapouite/originals/meal.html

See http://game-icons.net/tags/food.html for other options that could suit your view. These drinking and eating icons try to emphasize the action.
