### ISSUE TITLE
Dwarf face with skin

### ISSUE THREAD

**Issue by spikebarnett** [game-icons/icons#252]
A version of http://game-icons.net/delapouite/originals/dwarf-face.html that has skin instead of a void, to fit more in line with these.

http://game-icons.net/delapouite/originals/woman-elf-face.html
http://game-icons.net/delapouite/originals/wizard-face.html

**Comment by Delapouite** [comment]
Yes. Historically, the dwarf was made before the others, so it looks a bit off in comparison.

**Comment by Delapouite** [comment]
Done: http://game-icons.net/delapouite/originals/dwarf-face.html
