### ISSUE TITLE
Exploding/cracked/broken Planet

### ISSUE THREAD

**Issue by billmartinson** [game-icons/icons#253]
I could really use a simplified "exploding planet" kind of icon. Something that's still recognizable as such when reduced down to 32x32. Here's a very rough mockup (well, more of a hackup) of the general idea:

![broken planet idea](https://cloud.githubusercontent.com/assets/2751745/19908014/b2a59a5a-a057-11e6-9f79-64e2d331956b.png)
Ideally it would have a generally circular footprint, and not require any kind of "bordering," because the icons in my game are freestanding, unbounded. I'm looking for something that will fit into the areas where I currently have these alien skulls (which BTW I found on game-icons and slightly modified to put bone around the outside of the eye sockets and to add 3D beveling).

![tempilloskulls](https://cloud.githubusercontent.com/assets/2751745/19908108/27638550-a058-11e6-81c8-70ed8733f383.png)

The end goal would look something roughly like this. Obviously my hackup is too detailed and messy for the concept to translate well.

![testcrackedplanet](https://cloud.githubusercontent.com/assets/2751745/19908308/11800726-a059-11e6-97d1-f8fc7b882141.png)

**Comment by billmartinson** [comment]
Thanks, @Delapouite. I tried to figure out how to add the request label, but came up empty-handed.

**Comment by Delapouite** [comment]
https://game-icons.net/1x1/delapouite/exploding-planet.html
