### ISSUE TITLE
Inkscape fails to load d10 svg

### ISSUE THREAD

**Issue by schoepft** [game-icons/icons#256]
Inkscape fails to load the d10 svg.

Inkscape 0.91
http://game-icons.net/skoll/originals/d10.html

![d10_inkscape91](https://cloud.githubusercontent.com/assets/18472012/20248234/6d9221f4-a994-11e6-9022-2b743d8130eb.png)

**Comment by schoepft** [comment]
Same deal with the d12.  The d8 and d20 are fine though.

http://game-icons.net/skoll/originals/d12.html

![d12_inkscape91](https://cloud.githubusercontent.com/assets/18472012/20248304/f0c917e8-a995-11e6-8f16-2d94a052333a.png)

**Comment by Delapouite** [comment]
This is a bug in InkScape 0.91 which has problems handling negative numbers in paths.

This is fixed in the upcoming 0.92 currently in beta.
