### ISSUE TITLE
GreenSkins

### ISSUE THREAD

**Issue by SuperKamiChazz** [game-icons/icons#262]
Looking for a few icons for 
orcs
goblins
trolls 
ogres
Maybe a goblin camp?

**Comment by Delapouite** [comment]
Hi. The first image I have in mind for this, is some kind of war-tent with wooden spikes and giant tusks.

**Comment by SuperKamiChazz** [comment]
that would be great!!! I'm currently making a board game and I've got to the prototype stage so images are a big thing i need for the cards and tokens a war camp is a must have!

**Comment by Delapouite** [comment]
Will be associated with this demand for a human camp https://github.com/game-icons/icons/issues/132

**Comment by Delapouite** [comment]
A goblin war tent has been released : http://game-icons.net/delapouite/originals/goblin-camp.html
