### ISSUE TITLE
Food Icons: Peanuts, Beets, Potatoes and more!

### ISSUE THREAD

**Issue by vorgrist** [game-icons/icons#263]
I'd love more food icons! Thanks!

**Comment by Delapouite** [comment]
Potato : http://game-icons.net/delapouite/originals/potato.html
Chili pepper : http://game-icons.net/delapouite/originals/chili-pepper.html

**Comment by Delapouite** [comment]
Peanut http://game-icons.net/rihlsul/originals/peanut.html

**Comment by Delapouite** [comment]
Beet: http://game-icons.net/delapouite/originals/beet.html

I'm closing this thread for now. Feel free to create a new one with specific food.
