### ISSUE TITLE
Swamp Icon not Downloading

### ISSUE THREAD

**Issue by nancyjanderson** [game-icons/icons#269]
Hi there,
  Not sure what I am doing wrong of if there is a bug on the site. 

When I try to download the swamp icon I get a blank file. 
http://game-icons.net/delapouite/originals/swamp.html

Tried it a couple of different ways, no luck. 

However, I downloaded several other icons from the site and they all were fine. 

Thanks,
nja

**Comment by Delapouite** [comment]
Hi. 

What is your browser? 
Which formats did you try downloading: SVG or PNG?
Did you play with the color editor before?

Thanks!

**Comment by nancyjanderson** [comment]
Ack! missed your reply. 

Firefox v. 50+
SVG using Inkscape 0.91 to download
Most likely I switched it to a transparent background before downloading. 

Today I am having trouble with the Lee Enfield icon (http://game-icons.net/skoll/originals/lee-enfield.html). It downloads but only a small bit of the rifle barrel is in the file (and the background). 

Same thing happens if I use Chrome to download either the swamp or Lee Enfield icon file. 

Thanks,
nja

**Comment by nancyjanderson** [comment]
Upgraded Inkscape to .92 and was able to open both files. 

Yay!
