### ISSUE TITLE
Discuss: Integrate with Expedition quests

### ISSUE THREAD

**Issue by toddmedema** [game-icons/icons#270]
Hello!

I'm the creator of [Expedition](http://expeditionrpg.com), an open source RPG with a companion app that allows anyone to write their own choose-your-own-adventures.

We've been [talking about](https://github.com/Fabricate-IO/expedition-quest-creator/issues/46#issuecomment-267146211) giving creators the tools to use custom icons in their quests, and game-icons' set of games would be a perfect fit! We would, of course, give credit to game-icons and the icon creators.

Let me know! Seems like we'd just need an API endpoint by which to programmatically fetch icons as they're included in the quests.

**Comment by toddmedema** [comment]
Or, another option would be for us to download all of the icons and host them for our creators to access. I believe that's allowed as-is with the game-icons license, but I'd still like to get your permission out of respect for a fellow creator.

**Comment by Delapouite** [comment]
Hi Todd.

Expedition looks great, congrats!

Currently we do not provide any API to retrieve the icons. game-icons.net pages are statically generated so there's no real server logic to query.

So for now I guess the best option for your project is the one you described: host the icons on your servers, and regularly check for updates to grab the newest one.

I'll post here if I ever start making any progress on a API.

Thanks.
