### ISSUE TITLE
Commodities for catan

### ISSUE THREAD

**Issue by wvanderp** [game-icons/icons#272]
there are Commodities in the catan expention cities and knights. i would apriciate if these items could be made in the same style of the resources. http://game-icons.net/games/catan.html

these are the cards: http://www.catan.com/files/styles/lightboxy/public/gallery/ck_commodities_lr.png?itok=hKJ3k9u2

**Comment by Delapouite** [comment]
Hi.

I've added the coins and paper commodities to the page : http://game-icons.net/games/catan.html
I'll add cloth soon.

**Comment by Delapouite** [comment]
Here comes the cloth http://game-icons.net/delapouite/originals/rolled-cloth.html
