### ISSUE TITLE
Shield Bash

### ISSUE THREAD

**Issue by matej-zajacik** [game-icons/icons#273]
An attack with a shield to push or stun the enemy. Thanks :)

Refs:

- http://vignette3.wikia.nocookie.net/soada/images/0/04/AbilityIcon-ShieldBash-Normal.jpg/revision/latest?cb=20140319010913
- http://t13.deviantart.net/tIXpsWq1AgmltXIfjROiT0CSIyU=/fit-in/700x350/filters:fixed_height(100,100):origin()/pre06/a9f1/th/pre/f/2009/114/f/9/tyr__s_warding_by_thefirstangel.jpg
- https://shadowerajp.files.wordpress.com/2012/03/069-shield-bash.jpg?w=328

**Comment by Delapouite** [comment]
Here's a shield bash http://game-icons.net/delapouite/originals/shield-bash.html
