### ISSUE TITLE
Motion picture film icons

### ISSUE THREAD

**Issue by DrPhibes99** [game-icons/icons#275]
It would be nice to have icons of motion picture film:

- [x] spool of film
- [x] stripe of film
- [x] film camera
- [x] film projector

Thank you very much for your great work!

**Comment by Delapouite** [comment]
A film projector : http://game-icons.net/delapouite/originals/film-projector.html

**Comment by Delapouite** [comment]
A video camera http://game-icons.net/delapouite/originals/video-camera.html

**Comment by Delapouite** [comment]
Director chair http://game-icons.net/delapouite/originals/director-chair.html

**Comment by Delapouite** [comment]
A film strip http://game-icons.net/delapouite/originals/film-strip.html

**Comment by Delapouite** [comment]
A film spool http://game-icons.net/delapouite/originals/film-spool.html
