### ISSUE TITLE
Slime/ooze icon

### ISSUE THREAD

**Issue by Caellian** [game-icons/icons#276]
I was really surprised that the one of most common game enemy was missing. Please add slimes, thank you! <3

**Comment by Delapouite** [comment]
Here comes a transparent slime : http://game-icons.net/cathelineau/originals/transparent-slime.html
And a opaque one : http://game-icons.net/delapouite/originals/slime.html

The gooey monster is related : http://game-icons.net/lorc/originals/gooey-daemon.html

**Comment by gameiconthrowaway** [comment]
Thanks, I had wanted these too. They look good.
