### ISSUE TITLE
More Plant Icons (Cotton, Flax etc.)

### ISSUE THREAD

**Issue by LordPeter** [game-icons/icons#277]
Hi,
so I have been working on a Medieval Economy themed mod for a game, and your icons have been an invaluable help.
However, I am still missing a few icons to have everything covered. If they could be made, I would be most grateful. Here is the first bunch, Plants:

- [x] Cotton
- [x] Flax
- [x] Hemp
- [x] Sugar Cane
- [x] Poppy
- [x] Sesame
- [x] Almonds

**Comment by rihlsul** [comment]
2nd on the Sugar.  BTW, Delapouite - thanks for how fast I've seen you fulfill these.  :D

**Comment by Delapouite** [comment]
Here comes the sugar canes : http://game-icons.net/delapouite/originals/sugar-cane.html
Bonus: a bag to store the sugar : http://game-icons.net/delapouite/originals/powder-bag.html

**Comment by LordPeter** [comment]
Wow, I must agree, that was like -really- fast :D
Looking forward to the other ones (take your time though).
The sugar cane icon is looking pretty... sweet so far ^^

**Comment by Delapouite** [comment]
Cotton flower: http://game-icons.net/delapouite/originals/cotton-flower.html

**Comment by Delapouite** [comment]
Almond: http://game-icons.net/delapouite/originals/almond.html

**Comment by Delapouite** [comment]
Flax https://game-icons.net/delapouite/originals/flax.html

**Comment by Delapouite** [comment]
And finally the sesame seeds https://game-icons.net/1x1/delapouite/sesame.html
