### ISSUE TITLE
More Animal Product Icons (Butter, Wool etc.)

### ISSUE THREAD

**Issue by LordPeter** [game-icons/icons#278]
In order to keep the requests readable, I will bundle things together that belong to a certain theme.
Here is the next bunch, Animal Products:

- [x] Butter
- [x] Wool
- [x] Camel Hair  (a bit specific, I guess a general "strand of hair" would be fine and still usable in other projects)
- [x] Ivory  (elephant tusks)

**Comment by Delapouite** [comment]
Ivory tusks : http://game-icons.net/delapouite/originals/ivory-tusks.html
Wool: http://game-icons.net/delapouite/originals/wool.html

**Comment by Delapouite** [comment]
Milk: http://game-icons.net/rihlsul/originals/milk-carton.html

**Comment by Delapouite** [comment]
Strand of hair : http://game-icons.net/delapouite/originals/hair-strands.html

**Comment by Delapouite** [comment]
Butter http://game-icons.net/delapouite/originals/butter.html

**Comment by Delapouite** [comment]
Yarn: https://game-icons.net/1x1/delapouite/yarn.html
