### ISSUE TITLE
pc, consoles

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#28]
http://forum.game-icons.net/request-system-platform-icons-for-desktop-mobile-console

**Comment by aricooperdavis** [comment]
I'd also be interested in icons of this theme; like a laptop, desktop, monitor, or tower. Cheers!

**Comment by Delapouite** [comment]
a retro controller has been addded : http://game-icons.net/skoll/originals/retro-controller.html

**Comment by Delapouite** [comment]
http://game-icons.net/skoll/originals/console-controller.html

**Comment by Delapouite** [comment]
a desktop pc : http://game-icons.net/skoll/originals/pc.html

**Comment by Delapouite** [comment]
game console http://game-icons.net/delapouite/originals/game-console.html
