### ISSUE TITLE
More Weather Icons (Sandstorm, Fog)

### ISSUE THREAD

**Issue by LordPeter** [game-icons/icons#280]
I tried to use other icons, but it doesn't look good. These are the only two types of weather I can think of that are missing:

- [x] Sandstorm
- [x] Fog

**Comment by Delapouite** [comment]
https://game-icons.net/delapouite/originals/fog.html

**Comment by Delapouite** [comment]
Sandstorm https://game-icons.net/1x1/delapouite/sandstorm.html
https://www.youtube.com/watch?v=y6120QOlsfU

**Comment by LordPeter** [comment]
Awesome, thanks again for your work.
Oh and right, that was the name of that song I was looking for - thx for reminding me! ;)
