### ISSUE TITLE
Mars Rovers

### ISSUE THREAD

**Issue by BuckSavage** [game-icons/icons#282]
Icons with Mars rovers like pathfinder and Curiosity would be great!

Regards

**Comment by Delapouite** [comment]
Hi.

Pathfinder : http://game-icons.net/delapouite/originals/mars-pathfinder.html
Curiosity : http://game-icons.net/delapouite/originals/mars-curiosity.html

**Comment by BuckSavage** [comment]
Those are fantastic! Thank you.

**Comment by BuckSavage** [comment]
Those are awesome, thank you so much!
