### ISSUE TITLE
Borders for icons

### ISSUE THREAD

**Issue by CatZeyeS** [game-icons/icons#283]
Just an idea:
As you already managed to create shadows for your icons, borders would be a nice feature, too.
You know, not the frames, but those lines along the borders of the icons per se ..

Just a thought :)

Kind regards,
Kai

**Comment by Delapouite** [comment]
Hi

I've added this option. It's the stroke checkbox in the Foreground section. You can specify the width and color.
On some large plain icon, it will look fine, on other more detailed shapes it may not look that good.

Unfortunately in SVG there's no way to specify if the stroke should be set inside or outside the shape.
