### ISSUE TITLE
fencer / fencing request

### ISSUE THREAD

**Issue by gameiconthrowaway** [game-icons/icons#285]
Fencing, also called Olympic fencing, is a sport in which two competitors fight using 'Rapier-style' swords, winning points by making contact with their opponent.

How about an icon inspired by this public domain svg:
https://en.wikipedia.org/wiki/Fencing#/media/File:Fencing_pictogram.svg

**Comment by Delapouite** [comment]
A fencer : http://game-icons.net/delapouite/originals/fencer.html

**Comment by gameiconthrowaway** [comment]
Thank you this is perfect

**Comment by gameiconthrowaway** [comment]
Will this icon be added to the github repository? I don't see it in https://github.com/game-icons/icons/tree/master/delapouite/originals/svg
