### ISSUE TITLE
tiger

### ISSUE THREAD

**Issue by gameiconthrowaway** [game-icons/icons#286]
There's a tiger icon http://game-icons.net/delapouite/originals/tiger.html but something is wrong with the drawing. I don't know what. It looks more like a zebra. In my app I'm using one of the cat icons in place of the tiger icon.

**Comment by Delapouite** [comment]
You're right, this tiger is a bit lame. Here comes another one http://game-icons.net/delapouite/originals/tiger-head.html

**Comment by gameiconthrowaway** [comment]
Thank you!
