### ISSUE TITLE
Foods:  peanut / milk bottle / chocolate bar

### ISSUE THREAD

**Issue by rihlsul** [game-icons/icons#287]
Working on a Roblox game, been adding lots from the library (with attrib, love you guys), need a few others to round out the current set:

- peanut
- milk bottle
- chocolate bar

**Comment by rihlsul** [comment]
Oh  Peanut is also on #263 .  Tagging to connect.

**Comment by rihlsul** [comment]
If the pull request is acceptable quality, we can close this one.

**Comment by Delapouite** [comment]
Hi rihlsul !

Thanks a lot for your pull request.

I had to tweak your icons a bit so they can follow the look and feel of the collection. (You draw them in negative, using only strokes).

Chocolate bar : http://game-icons.net/rihlsul/originals/chocolate-bar.html
Peanut : http://game-icons.net/rihlsul/originals/peanut.html
Milk carton: http://game-icons.net/rihlsul/originals/milk-carton.html

**Comment by rihlsul** [comment]
Cool - thank you.  My first ever vector graphics / SVGs.  :D

I get the difference of what you mean about the negative (yours definitely are better).  I'll keep that in mind if I make any more.
