### ISSUE TITLE
mermaid

### ISSUE THREAD

**Issue by gameiconthrowaway** [game-icons/icons#289]
A mermaid is a legendary aquatic creature with the head and upper body of a female human and the tail of a fish. Mermaids appear in the folklore of many cultures worldwide, including the Near East, Europe, Africa and Asia.

**Comment by Delapouite** [comment]
Here comes the mermaid : http://game-icons.net/delapouite/originals/mermaid.html

**Comment by gameiconthrowaway** [comment]
Thank you! It looks good!
