### ISSUE TITLE
more humanoid fairy

### ISSUE THREAD

**Issue by gameiconthrowaway** [game-icons/icons#291]
There is already a good fairy icon http://game-icons.net/lorc/originals/fairy.html. An additional icon with more human-like features (neck, head, legs, etc.) would be nice too.

**Comment by Delapouite** [comment]
Here it comes http://game-icons.net/delapouite/originals/fairy.html

**Comment by gameiconthrowaway** [comment]
Thanks! Will this icon be added to the github repo? I could not find it in https://github.com/game-icons/icons/tree/master/delapouite/originals/svg
