### ISSUE TITLE
plain body

### ISSUE THREAD

**Issue by gameiconthrowaway** [game-icons/icons#293]
The page http://game-icons.net/tags/body.html shows many different body effects. Could a body icon with no effect be added as well? An example of what I have in mind would be like http://game-icons.net/delapouite/originals/body-height.html but without the arrows or like http://game-icons.net/lorc/originals/aura.html but without the aura. I know that I could edit the svg to remove the arrows or aura on my own computer but still...

**Comment by Delapouite** [comment]
Here's a plain body : http://game-icons.net/delapouite/originals/person.html

**Comment by gameiconthrowaway** [comment]
Excellent!
