### ISSUE TITLE
Porcelain/Chinaware

### ISSUE THREAD

**Issue by LordPeter** [game-icons/icons#299]
An important historical trading good, nowadays often smashed in comedy films (https://en.wikipedia.org/wiki/Chinese_ceramics).
The most iconic and recognizable item would probably be a vase, something like this: https://commons.wikimedia.org/wiki/File:Kinesisk_porslinsflaska_fr%C3%A5n_1645-1655_-_Hallwylska_museet_-_95597.tif

**Comment by Delapouite** [comment]
A covered jar http://game-icons.net/delapouite/originals/covered-jar.html

**Comment by Delapouite** [comment]
Porcelain vase http://game-icons.net/delapouite/originals/porcelain-vase.html
Painted pottery http://game-icons.net/delapouite/originals/painted-pottery.html
