### ISSUE TITLE
Local conversion to PNG of rabbit with inkscape and imagemagick shows only head

### ISSUE THREAD

**Issue by cirosantilli** [game-icons/icons#300]
I know nothing about images, and this might not be your bug, but here it is:

![rabbit](https://cloud.githubusercontent.com/assets/1429315/22167661/d0d4bdb6-df5f-11e6-8114-dfc17648dfaf.png)

Conversion commands:

    convert delapouite/originals/svg/rabbit.svg -resize 512 ~/bak/git/general-game-ai/rabbit.png
    inkscape -z -e rabbit.png -w 1024 -h 1024 delapouite/originals/svg/rabbit.svg

on Ubuntu 16.10 (imgemagic 6.8.9, inkscape 0.91).

**Comment by Delapouite** [comment]
Hi. This is a bug in the way inkscape 0.91 handles negative numbers in paths.

I encourage you to update to the 0.92 version released on the 4th of January : https://inkscape.org/en/news/2017/01/04/inkscape-version-092-released/

It should be available in the next Ubuntu in April or you can point to the right PPA right now.

**Comment by cirosantilli** [comment]
Ah, if it's a known issue, then cool, let's close this.

Any clues about imagemagick? I can't even find if they use the same svg implementation.
