### ISSUE TITLE
Use multiple separate paths, allow customizing the color of each component, and give a default color

### ISSUE THREAD

**Issue by cirosantilli** [game-icons/icons#301]
I know this is huge and will never be done, but I have a dream!

Because apple stems are brown, and apples are red.

If we had this, the path split could be done easily from current data: http://stackoverflow.com/questions/33836224/splitting-svg-paths-programmatically

Inkscape has a path split thing: http://stackoverflow.com/questions/8753206/split-shape-defined-by-path-into-sub-paths but I can't use it properly to separate the apple stem.

**Comment by Delapouite** [comment]
I will have to investigate how to do it in JavaScript so it can be integrated directly on the website editor.

But I just tried in InkScape and it worked. I used this icon as a starting point : 
http://game-icons.net/lorc/originals/shiny-apple.html

I selected the whole foreground, then use the `Path > Break Apart` command and was able to apply different colors for the apple, the stem and the shiny effect on the right.

**Comment by cirosantilli** [comment]
Yes, I was trying with that apple.

Humm, after "break apart", the apple disappears, only black background shows, and outlines reappear when I hover them. But I wasn't able to bucket fill anything.

Also I notice that bucket fill is really glitchy on that image for some reason, sometimes it fills things, others not. Maybe because of my old version.

Another option for the Js would be to just plug it into: https://github.com/SVG-Edit/svgedit

**Comment by Delapouite** [comment]
Good news, I managed to emulate the break apart function with a mix of JS and DOM voodoo : https://delapouite.github.io/svg-break-apart/

Next step: integrate this in the studio.

**Comment by cirosantilli** [comment]
@Delapouite awesome!!!

**Comment by Delapouite** [comment]
Should be good now. I even displayed the apple example : https://github.com/game-icons/icons/issues/246#issuecomment-284718120
