### ISSUE TITLE
delapouite/originals/svg/brick-wall.svg has some whitespace on top

### ISSUE THREAD

**Issue by cirosantilli** [game-icons/icons#302]
The vertical bars go above the top horizontal bar (only at the top).

Inkscape zoom:

![screenshot from 2017-01-21 17-11-38](https://cloud.githubusercontent.com/assets/1429315/22176217/2f5a8c10-dffd-11e6-8ddd-91cf7acea455.png)

This becomes very visible when the background is black and is different from other icons which have all back background:

![screenshot from 2017-01-21 17-12-16](https://cloud.githubusercontent.com/assets/1429315/22176221/436aa474-dffd-11e6-8651-f2f703b0163b.png)

Same happens on the Js raster: http://game-icons.net/delapouite/originals/brick-wall.html

The line is so thin, that at 512px it dithers to gray, and I can get rid of it with:

    convert "$${png}" -threshold 90% -transparent white "$${png%%.*}.png" ;\

**Comment by Delapouite** [comment]
Yes, they were stray vertex. It shoud be better now.

As an apology, here's a new icon, broken wall: http://game-icons.net/delapouite/originals/broken-wall.html

**Comment by cirosantilli** [comment]
@Delapouite haha, you're awesome :smile:
