### ISSUE TITLE
Wheelbarrows and Wagons

### ISSUE THREAD

**Issue by vasior** [game-icons/icons#303]
I'd really appriciate wheelbarrow and wagon icons included on this great site

**Comment by Delapouite** [comment]
Hi vasior.

We already provide a wheelbarrow http://game-icons.net/delapouite/originals/wheelbarrow.html

and several wagons : 

http://game-icons.net/delapouite/originals/coal-wagon.html
http://game-icons.net/delapouite/originals/old-wagon.html
http://game-icons.net/delapouite/originals/mine-wagon.html

Do you need another one?

**Comment by vasior** [comment]
My mistake, I was looking in the wrong section. Those icons look great

**Comment by Delapouite** [comment]
No worries. 
Sections are not always that good and is in constant improvement.
You can use the search engine on the top right corner to find what you need.
