### ISSUE TITLE
Spell Book

### ISSUE THREAD

**Issue by TexasNeo** [game-icons/icons#306]
I would like a spell book, something like:
https://www.iconfinder.com/icons/1161510/book_magic_manual_open_spell_spells_tome_icon#size=128
or 
https://www.shutterstock.com/image-vector/incantation-icon-magic-book-wand-thin-451095565

**Comment by Delapouite** [comment]
Hi, a spell book joins the library : http://game-icons.net/delapouite/originals/spell-book.html
