### ISSUE TITLE
Heptagram / Heptacle

### ISSUE THREAD

**Issue by mpascall** [game-icons/icons#307]
I'd love to see 7 pointed versions of the Pentrams/Pentacles that are here.  

Like they use in Game of Thrones: [http://winteriscoming.net/2016/05/03/game-of-thrones-screencap-breakdown-home/2/](http://winteriscoming.net/2016/05/03/game-of-thrones-screencap-breakdown-home/2/)

Thanks!!

edited to correct the link

**Comment by Delapouite** [comment]
Hi.

Here comes an Heptagram : http://game-icons.net/delapouite/originals/heptagram.html

**Comment by mpascall** [comment]
That is awesome.  Thank you!!
