### ISSUE TITLE
Thrust left.

### ISSUE THREAD

**Issue by perlDreamer** [game-icons/icons#311]
I'd like an arrow like the thrust arrow, except that it would curve left, like a frisbee throw.

**Comment by Delapouite** [comment]
Hi perlDreamer

Could you add a link to the *thrust arrow* you describe? Is it this one: http://game-icons.net/lorc/originals/thrown-spear.html?

**Comment by perlDreamer** [comment]
It's this one:

http://game-icons.net/felbrigg/arrows/thrust.html

**Comment by Delapouite** [comment]
Here's a bended arrow. You can use the online editor to do a mirror effect in the direction you want.

http://game-icons.net/delapouite/originals/thrust-bend.html
