### ISSUE TITLE
Mars base

### ISSUE THREAD

**Issue by BuckSavage** [game-icons/icons#314]
Hi, 
I'm looking for icons for Mars base parts.
- [x] Habitat Dome
- [x] Solar panels 
- [x] Greenhouse
- [x] Fuel tanks
- [x] Refinery

Anything along those lines.

Thanks for all the great icons you provide!

**Comment by gameiconthrowaway** [comment]
solar panels http://game-icons.net/skoll/originals/solar-power.html

**Comment by Delapouite** [comment]
Habitat dome : http://game-icons.net/delapouite/originals/habitat-dome.html

**Comment by Delapouite** [comment]
Green house http://game-icons.net/delapouite/originals/greenhouse.html

**Comment by Delapouite** [comment]
Fuel tank : http://game-icons.net/delapouite/originals/fuel-tank.html

**Comment by Delapouite** [comment]
And finally the refinery http://game-icons.net/delapouite/originals/refinery.html

**Comment by BuckSavage** [comment]
The Icons are fantastic.

Thank you!
Don
