### ISSUE TITLE
section underlay "icons" for icon groups

### ISSUE THREAD

**Issue by sparr** [game-icons/icons#318]
Consider the dice icons. I would like one icon that is just the square with no pips.

Consider the playing card icons. I would like one icon that is white where the suit icons are on the cards, and another icon that is white where the rank letter/number is on the cards.

Consider the battery icons. I would like one icon that is the outline, filled in.

The blank die and solid battery would be useful icons on their own, but that's not why I'm asking. My use case for these is for color layering. I'd like to be able to make dice with colored pips, without also coloring the negative space in the corners. I'd like to be able to programmatically make cards with colored suits without also coloring the rank and negative space in the corners. I would accomplish this by loading the meta-icon and coloring it, then loading the real icon on top of it in W/T mode.

**Comment by Delapouite** [comment]
Hi

Yes, that would be awesome. It requires a lot of SVG wizardry to do so, because currently all paths are fused. But I'm definitely interested in exploring this challenge in the near future.

Related topic: https://github.com/game-icons/icons/issues/301

**Comment by sparr** [comment]
This isn't quite the same request as #301. Rather than having multiple paths in one SVG, I'm asking for a few new whole icons, which could be SVG or rendered to a raster format, which could be layered with the existing icons for multi coloring, without having to do SVG manipulation otherwise.
