### ISSUE TITLE
Music Toggle on/off 

### ISSUE THREAD

**Issue by VaelVictus** [game-icons/icons#320]
Hello, here you have excellent "sound on/off" icons.

http://game-icons.net/tags/sound.html

But so often in my games, I want to offer a way to turn the music off and keep the sound on. (and vice versa) I would like to request a musical note with an x next to it. Ideally the ♫ note. So, **♫))** for on and **♫x** for off.

**Comment by Delapouite** [comment]
Hello.

Here are some on/off toggles : 

http://game-icons.net/delapouite/originals/sound-on.html
http://game-icons.net/delapouite/originals/sound-off.html
