### ISSUE TITLE
Buy card / sell card

### ISSUE THREAD

**Issue by Geddd** [game-icons/icons#323]
Sell card...
Top left: Push coin (up-arrow + coin)
Bottom right: Pull card (card + down-arrow)

Buy card...
Top left: Push card (up-arrow + card)
Bottom right: Pull coin (coin + down-arrow)

**Comment by Delapouite** [comment]
Buy card:  http://game-icons.net/delapouite/originals/buy-card.html
Sell card: http://game-icons.net/delapouite/originals/sell-card.html
