### ISSUE TITLE
Open source the Studio code

### ISSUE THREAD

**Issue by perlDreamer** [game-icons/icons#328]
I'm not likely to be of any use for making icons, but I know enough Javascript to be able to fix bugs or add features.  Please consider adding open sourcing the studio code so folks from the community can help out.

**Comment by Delapouite** [comment]
Thanks for the offer!

There's really nothing secret about this online editor. It's just a mix of React components, a Redux store and some SVG fu : https://github.com/Delapouite/svg-break-apart

So it may be open-sourced in the future, but I will need to make it independent from the overall site before.

In the meantime, feel free to submit your bugs and suggestions and I'll work on it if it's technically possible.
