### ISSUE TITLE
Weed

### ISSUE THREAD

**Issue by DrKran** [game-icons/icons#332]
Can you make all kinds of drugs?

**Comment by Delapouite** [comment]
Hi. There's already http://game-icons.net/delapouite/originals/hemp.html for cannabis and tobacco is in poison http://game-icons.net/tags/poison.html

Seringues can be found here : http://game-icons.net/tags/chemical.html

Which drugs are missing?

**Comment by Delapouite** [comment]
Closing for now. Feel free to open new issues with more concrete examples.

**Comment by Guard13007** [comment]
Cocaine? Heroin? Crystal Meth?
