### ISSUE TITLE
Abacus, Counting/Tallying

### ISSUE THREAD

**Issue by Tickthokk** [game-icons/icons#334]
I'd really like to see an Abacus or something else to indicate "counting" or "tallying".

https://en.wikipedia.org/wiki/Abacus

Thanks!

**Comment by Delapouite** [comment]
Hi Nick.

Here's one http://game-icons.net/delapouite/originals/abacus.html

**Comment by Tickthokk** [comment]
Thanks!  It wasn't showing up on the search, but now I'm seeing it.
