### ISSUE TITLE
GOBLINS

### ISSUE THREAD

**Issue by SuperKamiChazz** [game-icons/icons#338]
Looking for a few icons for goblins like bandits a leader maybe a scout and mage?

**Comment by Delapouite** [comment]
Here comes a goblin : http://game-icons.net/delapouite/originals/goblin-head.html

**Comment by SuperKamiChazz** [comment]
wow thats perfect any chance of an ogre and a troll?

**Comment by Guard13007** [comment]
@SuperKamiChazz You should probably make a new issue for those requests. Since this is closed, it may not get looked at again or easily be forgotten.
