### ISSUE TITLE
manual orange juicer

### ISSUE THREAD

**Issue by HeavenlyDog** [game-icons/icons#346]
Greetings to Delapouite, and other authors who collaborate on this wonderful page. First of all let me tell Delapuite that I am designing a semi-collaborative board game, dungeon game, and for children from 5 years old onwards. I am going to use icons from this page, and also drawings of Lorc, whom I will write soon to warn you.
Having said that, I proceeded to make my order of the month: Would an icon of a manual orange juicer be possible? ^^
Thanks in advance. And a cordial greeting.

**Comment by HeavenlyDog** [comment]
Regards, again.
First of all I apologize, since I must withdraw from my claim, and correct it. If possible, the icon of the juicer that would be closest to what I need one of this type:
Https://www.google.com/search?q=black+icon+juicer&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_6YOl0KfTAhUGuxQKHenHD5QQ_AUIBigB&biw=1366&bih=631#tbm=isch&q=lime+juicer
Cheers and thank you again.

**Comment by HeavenlyDog** [comment]
y

**Comment by Delapouite** [comment]
Hello HeavenlyDog.

The manual orange juicer is ready : http://game-icons.net/delapouite/originals/manual-juicer.html
