### ISSUE TITLE
Subway icon

### ISSUE THREAD

**Issue by Guard13007** [game-icons/icons#350]
Something like the train cars typically used in subways.

![](http://nycsubway.org.s3.amazonaws.com/images/icon/title_ny_independent.jpg)

![](http://www.sambadrome.com/wp-content/uploads/Screen-Shot-2012-10-04-at-12.37.33-AM.png)

![](https://upload.wikimedia.org/wikipedia/commons/0/03/Toronto_Subway_Train4.jpg)

**Comment by DarkZaitzev** [comment]
I'll try

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/subway.html

**Comment by Delapouite** [comment]
Another subway icon is available https://game-icons.net/1x1/caro-asercion/subway-train.html
