### ISSUE TITLE
Lemon/Lime

### ISSUE THREAD

**Issue by DarkerStix** [game-icons/icons#353]
I'm designing a game that requires fruit symbols and I have everything that I need except for a Lemon/Lime shaped fruit.

**Comment by Delapouite** [comment]
related: https://github.com/game-icons/icons/issues/346

**Comment by Delapouite** [comment]
Hi !

Here comes two icons about lemons : 

Lemon: http://game-icons.net/delapouite/originals/lemon.html
Cut lemon: http://game-icons.net/delapouite/originals/cut-lemon.html

**Comment by DarkerStix** [comment]
Thanks a bunch!!
