### ISSUE TITLE
Tags for icons

### ISSUE THREAD

**Issue by suvroc** [game-icons/icons#357]
Do you provide a set of tags associated with each icon? I saw that this is available on your page, but it is not in the repository.

I want to use it in my game and provides a user method to choose which icons do you want to see by some category.

**Comment by ckohnert** [comment]
I second this! I'm going to have to re-do all this hard work in a future project of mine if there's not an easy way to associate the images with their tags. Ideally it's something easy to parse, like a json file in the ZIP download.

**Comment by ckohnert** [comment]
I couldn't wait, so I wrote a quick scraper to extract them. It seems to do an okay job. Maybe it'll help whoever... https://gist.github.com/ckohnert/2edd80c6de11d55700887229a2335bae

**Comment by suvroc** [comment]
I created a simple app to choose icons and generate json file with tags https://github.com/suvroc/icon-chooser

**Comment by smrt28** [comment]
> I created a simple app to choose icons and generate json file with tags https://github.com/suvroc/icon-chooser

Hi, would be possible to publish the script somewhere? Thanks

**Comment by smrt28** [comment]
Just a shell script ;-)

```
#!/bin/bash
mkdir -p icons-tags
all_tags=$(curl -s https://game-icons.net/tags.html | tr '>' '\n'| grep html | grep tags | sed 's/.*\///' | sed 's/\.html.*//')

for tag in $all_tags; do
    echo $tag
    curl -s https://game-icons.net/tags/$tag.html | tr '>' '\n' | grep 'img src=.*svg.*class="icon' | sed 's/" .*//' | sed 's/.* src="//' > icons-tags/$tag.list
done
```

**Comment by suvroc** [comment]
My script is here: https://github.com/suvroc/icon-chooser/tree/master/src/assets/icons/IconScraper
