### ISSUE TITLE
Random icon button on site

### ISSUE THREAD

**Issue by Guard13007** [game-icons/icons#358]
It'd be fun when not sure exactly what I want to do to be able to click a button and see a random icon.

**Comment by Delapouite** [comment]
Yes. It's been requested several times, so I guess I'll need to find a simple way to do it.

**Comment by Guard13007** [comment]
@Delapouite Does the site have a dynamic backend or is it static? Dynamic should give you options, static may require something a little weirder (you could generate a page that uses JS to randomly select a page for a quick and dirty solution).

**Comment by Delapouite** [comment]
It's a static one, with the slight difficulty you describe. But nothing impossible.

**Comment by Delapouite** [comment]
Added in the footer.
