### ISSUE TITLE
Manual meat grinder

### ISSUE THREAD

**Issue by HeavenlyDog** [game-icons/icons#359]
Regards!
I could use an icon that represents a manual meat grinder. Thanks in advance.
P.S. By the way, great icons that are coming out. Much improved over the former.

**Comment by DarkZaitzev** [comment]
You mean the thing that has a circular lever or something like that?

**Comment by HeavenlyDog** [comment]
Yes, the typical and classic manual meat grinder.

https://www.google.es/search?q=manual+meat+grinder&source=lnms&tbm=isch&sa=X&sqi=2&ved=0ahUKEwjHjoii7YDUAhWMnBoKHUtBA1AQ_AUIBigB&biw=1366&bih=629

Thanks you, very much!

**Comment by Delapouite** [comment]
Here's one : http://game-icons.net/delapouite/originals/manual-meat-grinder.html
