### ISSUE TITLE
Set of lock picks

### ISSUE THREAD

**Issue by HeavenlyDog** [game-icons/icons#361]
Set of lock picks icon, please. ^^
https://www.google.es/search?q=juego+de+ganzúas&client=opera&site=webhp&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiHo6yiv-DTAhVCOBoKHSQTAjMQ_AUIBigB&biw=1366&bih=631
Greetings!

**Comment by DarkZaitzev** [comment]
I'll work in them...

**Comment by Delapouite** [comment]
He comes a few lockpicks http://game-icons.net/delapouite/originals/lockpicks.html
