### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#366]
Hello.

We introduce today a new feature in the Studio called "badges".

A picture is worth a thousand words:

![badges](https://cloud.githubusercontent.com/assets/39315/26416445/2e057054-40b6-11e7-86e7-41e90ae1bfbe.png)

You can now add a mini icon in your bigger icons! (There's a new section in the left sidebar to do it). It's up to you to find new possibilities.

A new page lists all the badges available http://game-icons.net/badges.html

More will be added to this small collection. Don't hesitate to make your suggestions in this thread.

### Planned badges

- [x] music note
- [x] leaf
- [x] skull
- [x] radioactive
- [x] money
- [x] up arrow
- [x] down arrow
- [x] user
- [x] crown
- [x] lock

**Comment by Delapouite** [comment]
Lock and radioactive have been added

**Comment by manuelhuber** [comment]
Resizing badges would be a great feature!

**Comment by Delapouite** [comment]
A new version of the Studio has been released.
Badges can now be dragged, rotated, scaled and mirror.
