### ISSUE TITLE
"Black cat" and "white cat" are not properly named

### ISSUE THREAD

**Issue by amishne** [game-icons/icons#375]
The names of "black cat" and "white cat" rely on white-on-black coloring; in other cases those names are inappropriate. In particular, with black-on-white coloring, the names are actually the reverse of what's displayed!

Better names are probably something like "hollow cat" or "cat outline" instead of "black cat" and maybe just "cat" instead of "white cat".

**Comment by Delapouite** [comment]
You're right. Their naming is more of an historical incident, dating back from the days where the icons were used as-is, without color tweaking.

**Comment by Delapouite** [comment]
Done

https://game-icons.net/1x1/lorc/cat.html
https://game-icons.net/1x1/lorc/hollow-cat.html
