### ISSUE TITLE
Request: Space smuggler Face

### ISSUE THREAD

**Issue by JonyM90** [game-icons/icons#390]
Hi, I´m working in a SciFi board game. I use face icons for the characters, like ninja face, alien stare, one eyed, cyborg face, etc. And now i need a pilot of a space ship, o maybe some WWII pilot face (?) 
Thanks.
PD: I'm from Argentina, sorry for my english.

**Comment by JonyM90** [comment]
Something like this [https://s-media-cache-ak0.pinimg.com/736x/3d/f4/94/3df494cacbb5a55b8bcdeeb0c8b605aa.jpg](url) , but more like the icons in http://game-icons.net/.

**Comment by Delapouite** [comment]
Here's a pilot https://game-icons.net/1x1/delapouite/plane-pilot.html
