### ISSUE TITLE
Disc golf icons

### ISSUE THREAD

**Issue by perlDreamer** [game-icons/icons#392]
A disc
A basket
A bag/backpack

**Comment by Delapouite** [comment]
A frisbee has landed : http://game-icons.net/delapouite/originals/frisbee.html

**Comment by perlDreamer** [comment]
Thank you!

**Comment by Delapouite** [comment]
A basket: https://game-icons.net/delapouite/originals/disc-golf-basket.html
A bag: https://game-icons.net/delapouite/originals/disc-golf-bag.html
