### ISSUE TITLE
Oni icon please

### ISSUE THREAD

**Issue by kealran** [game-icons/icons#397]
How about a japanese Oni Icon. 
![image](https://user-images.githubusercontent.com/29967648/28235288-2615992a-68e1-11e7-98b3-dd11f0ae90e2.png)

Not sure how to add labels...or maybe I can't? Should go into the Ninja categorie I suppose.

**Comment by Delapouite** [comment]
Here comes an oni http://game-icons.net/delapouite/originals/oni.html
