### ISSUE TITLE
Sword in the stone

### ISSUE THREAD

**Issue by SuperKamiChazz** [game-icons/icons#405]
A sword in the stone 
knights of the round table style with runes on it maybe a little grass around it or moss?

**Comment by Delapouite** [comment]
related to http://game-icons.net/lorc/originals/sword-in-stone.html

**Comment by gameiconthrowaway** [comment]
the existing icon that Delapouite has linked worked fine for me, without grass/moss or runes

**Comment by SuperKamiChazz** [comment]
well i was wanting the grass and moss but thanks for your opinion

**Comment by Delapouite** [comment]
I tried doing some good moss without success. I'll try another day.
Meanwhile, here comes a sword in an altar : http://game-icons.net/delapouite/originals/sword-altar.html

**Comment by Delapouite** [comment]
An ancient sword covered with moss http://game-icons.net/delapouite/originals/ancient-sword.html
