### ISSUE TITLE
horn of plenty

### ISSUE THREAD

**Issue by Charlie808** [game-icons/icons#412]
Hello, 

first of all... amazing work! Thanks for sharing your art and making it available to everybody. It is very generous of you. I have a possible request for an icon which would be useful for many games imho:

"horn of plenty"... what do you think? ;-)

All the best,

Carlo

**Comment by Delapouite** [comment]
Hi Carlo

Nice idea. I see what you mean, something like that http://virtuellife.v.i.pic.centerblog.net/84f9ce06.gif

**Comment by Charlie808** [comment]
Exactly! :-) I am glad you like the idea thanks!

**Comment by gameiconthrowaway** [comment]
+1 this is also called https://en.wikipedia.org/wiki/Cornucopia and is connected to ancient Greece

**Comment by Charlie808** [comment]
hello, sorry to bother, I was wondering if anybody is working on this, I would like to you use it in a card game I am working on. Of course no problem if you are not, and thanks again for your amazing work!

**Comment by Delapouite** [comment]
Hello Charlie !

Here comes the horn : http://game-icons.net/delapouite/originals/cornucopia.html

**Comment by Charlie808** [comment]
thank you! 👍
