### ISSUE TITLE
Open-Source the Studio code?

### ISSUE THREAD

**Issue by RonPenton** [game-icons/icons#418]
I love what you're doing with this project. It's amazing. 

I would like to use your icons, and I have this idea that instead of customizing each and every one with the studio styles I select, could you possibly open-source the studio rendering code so that I could dynamically alter my icons appearance at runtime in my own app?

That would be amazing, thanks!

**Comment by RonPenton** [comment]
I went ahead and reverse-engineered the presets to make my own React components to do this: 

https://github.com/RonPenton/NotaMUD/blob/master/src/client/components/GameIcon.tsx

Feel free to close this issue.

**Comment by Delapouite** [comment]
I'm glad you found how to style SVGs in your project.
As you've done, it's juste a matter of rendering the proper attributes. So there's no magic in the studio, just simple *templating* and var substitution.

**Comment by psotos** [comment]
Great work!!
