### ISSUE TITLE
Request: Different types of Buckets

### ISSUE THREAD

**Issue by HorseReader** [game-icons/icons#423]
Empty wood bucket with a handle
Empty wood bucket without a handle
Empty metal bucket with a handle
Empty metal bucket without a handle

Filled wood bucket with a handle
Filled wood bucket without a handle
Filled metal bucket with a handle
Filled metal bucket without a handle

**Comment by Delapouite** [comment]
Hello. The 8 bucket types have been added: http://game-icons.net/recent.html
