### ISSUE TITLE
Plant Seeds

### ISSUE THREAD

**Issue by HorseReader** [game-icons/icons#426]
Apple tree seeds
Orange tree seeds
Wheat seeds
Strawberry seeds
Potato seeds
Pine tree seeds
Palm tree seeds
etc..

**Comment by Delapouite** [comment]
Wheat seed : 
- http://game-icons.net/delapouite/originals/grain.html
- http://game-icons.net/delapouite/originals/powder-bag.html

**Comment by HorseReader** [comment]
Those are bags of wheat flower (grounded up seeds) I need the seeds themselves to plant wheat from. Could be an image of 2-3 seeds.

**Comment by Delapouite** [comment]
Here are a bunch of seeds https://game-icons.net/1x1/delapouite/sesame.html
