### ISSUE TITLE
Icone for walking (a walking man)

### ISSUE THREAD

**Issue by yannickbattail** [game-icons/icons#432]
Hello,

There is an icon for running and sprint.
http://game-icons.net/lorc/originals/run.html
http://game-icons.net/lorc/originals/sprint.html
Can we have an icon for walking?
a walking man like the RUN icon.
Please

  Thanks for your great work!

**Comment by Delapouite** [comment]
Hi Yannick. Here comes a walking man http://game-icons.net/delapouite/originals/walk.html

**Comment by yannickbattail** [comment]
thank you
