### ISSUE TITLE
Fingers Crossed

### ISSUE THREAD

**Issue by GeneralAce135** [game-icons/icons#433]
Just a simple request for an image of a hand with it's fingers crossed.
I personally feel like it would look best with the fingers pointing to the bottom-right of the square, but that's just a styling opinion.

Thanks for the fantastic images you've all made already!

**Comment by Delapouite** [comment]
Published: http://game-icons.net/generalace135/originals/fingers-crossed.html

**Comment by RonPenton** [comment]
Just a heads up, my first impression from a distance was that I was being flipped off. 

Not a criticism, I definitely couldn't do better and don't have any particular suggestions on how to improve it, but I almost spit my drink into my cup when I saw it. Thought I'd let you know. 

Thanks for the work!

**Comment by psotos** [comment]
Totally agree on the flip off! I needs to be changed. So funny!

Peter Sotos
psotos@EpicProportionsTour.com
Cell: 714-904-7310

http://EpicProportionsTour.com
http://Facebook.com/EpicProportionsTour
http://Twitter.com/EpicPropTour
http://instagram.com/EpicProportionsTour

**Comment by GeneralAce135** [comment]
Yeah, the version that got uploaded definitely has that impression XD
In the version I submitted you could see the index finger coming out the other side of the middle finger, so it was a bit more obvious that it was mid finger crossed over index. I'm not positive why that detail was removed, other than the index finger is too long compared to the middle finger if you analyze it closely.
![fingers-crossed](https://user-images.githubusercontent.com/14170626/31697030-00b693fe-b383-11e7-980e-010a13701f56.png)

Thanks for that feedback though. Actually made me laugh out loud!

**Comment by GeneralAce135** [comment]
Yeah, it definitely does look like someone's getting flipped off!
In the version I submitted it did not look like that at all. I had the index finger visibly coming out from under the middle finger, so it was obvious it was mid finger crossed over index:
![fingers-crossed - copy](https://user-images.githubusercontent.com/14170626/31697113-8609fc1c-b383-11e7-961e-2006120d0540.png)
If you think about it the index is definitely way too long compared to the middle, so I can see why it might have been changed. Oh well.
Thanks for the feedback! I actually laughed out loud when I saw these comments in my inbox

**Comment by Delapouite** [comment]
Hello guys.

Thanks everyone to pointing me out to this obvious mistake. I first need to apologize to GeneralAce135 for this unfortunate missing finger tip which change the whole meaning of the icon.

During the scale adjustment (which is just before the compression and PNGs generations done locally), I involuntarily skip the finger tips wich was in a original `<path>` element in the original file, separated of the rest of the hand which was itself in an extraneous `<g>` path.

Well nothing extraordinary wrong or complicated, but I just missed the entirety of elements in the canvas while selecting them to do the flattening / merging.

Again sorry for the inconvenience, it should be fixed now (you may need to refresh your browser cache).
