### ISSUE TITLE
request south american mammal icons

### ISSUE THREAD

**Issue by gameiconthrowaway** [game-icons/icons#435]
- [x] [Giant anteater](https://en.wikipedia.org/wiki/Giant_anteater)
- [x] [Three-toed sloth](https://en.wikipedia.org/wiki/Three-toed_sloth)
- [x] [South American tapir](https://en.wikipedia.org/wiki/South_American_tapir)

**Comment by Delapouite** [comment]
A tapir has been added https://game-icons.net/1x1/delapouite/tapir.html

**Comment by Delapouite** [comment]
Anteater: https://game-icons.net/1x1/caro-asercion/anteater.html
Sloth: https://game-icons.net/1x1/caro-asercion/sloth.html
