### ISSUE TITLE
Uprising icon

### ISSUE THREAD

**Issue by HeavenlyDog** [game-icons/icons#436]
It would be great to have an icon similar to the Rally the troops icon, but instead of a flag and spears, intuit pitchforks, torches, sickles and / or scythes.
By the way, I wanted to comment on how much game-icons.net has been improving and evolving, not only in icon designs, but also in every possible way of coloring and altering the icons from the own website. Thank you all for the effort. Regards!

**Comment by Delapouite** [comment]
Here comes the uprising http://game-icons.net/delapouite/originals/uprising.html
