### ISSUE TITLE
On the Brink (between life and death)

### ISSUE THREAD

**Issue by matej-zajacik** [game-icons/icons#446]
When a person gets on the brink of life, like a near death experience, where their fate is being decided. Perhaps two sides, one living, one dead, the person stands in the middle. One half of their body is still in the living zone, looking healthy and strong, while the other half is in the dead zone, looking withered and weak. Light versus dark kind of thing.

**Comment by Delapouite** [comment]
Not quite what you asked, but here's a first attempt at "half-dead" icon: http://game-icons.net/delapouite/originals/half-dead.html

**Comment by matej-zajacik** [comment]
Heh, I like it! Thank you! Doing face rather than figure is probably better, as you can express more through face.
