### ISSUE TITLE
Black layer after downloading

### ISSUE THREAD

**Issue by Djlencio** [game-icons/icons#448]
After every download I open the SVG in Inkscape but it seems to be covered by a black layer and, not depending on the choosen colour settings, the background is transparent and the foreground is black.
How can I fix this?
Thanks

**Comment by SilentSin** [comment]
I get the same thing. White icon + transparent background = Black layer in Illustrator.

**Comment by Delapouite** [comment]
Thanks for the report. To investigate further I would need some help. Could you copy paste the content of the SVG you download in this github issue?

**Comment by SilentSin** [comment]
`<svg style="height: 512px; width: 512px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M0 0h512v512H0z" fill="rgba(0, 0, 0, 0)"></path><g class="" style="touch-action: none;" transform="translate(0,0)"><path fill="rgba(255, 255, 255, 1)" d="M253.938 16s-.116 5.61 0 14.47c.116-8.86 0-14.47 0-14.47zm0 14.47c-.465 35.427-4.82 125.15-36.594 138.31-31.437 13.024-95.04-50.706-120.28-77.905 24.6 27.913 82.115 97.995 69.092 129.438-13.138 31.722-100.9 35.99-135.78 36.437 34.88.446 122.638 4.747 135.78 36.47 13.2 31.863-46.11 97.757-70.125 122.624 24.537-24.197 89.464-83.88 121.314-70.688 31.777 13.162 36.13 101.667 36.594 136.594.453-34.932 4.746-123.502 36.562-136.594 32.305-13.293 106.245 48.2 132.844 71.72-26.05-24.104-94.274-91.384-80.906-123.657 13.058-31.53 101.93-35.98 138.125-36.47-36.192-.488-125.06-4.9-138.125-36.438-13.227-31.924 53.26-103.695 79.937-130.718-27.322 26.44-99.95 92.406-131.875 79.187-31.777-13.156-36.1-102.882-36.563-138.31zm168.437 59.124c6.673-6.457 10.72-10.656 10.72-10.656s-4.193 4.044-10.72 10.656zm58.188 167.156c9.406.127 15.437 0 15.437 0s-6.03-.128-15.438 0zm-57.22 160.125c6.012 5.562 9.75 8.844 9.75 8.844s-3.61-3.417-9.75-8.845zM253.938 481.75c-.113 8.723 0 14.25 0 14.25s.116-5.518 0-14.25zM96.03 415.844c-6.063 5.98-9.78 9.875-9.78 9.875s3.86-3.744 9.78-9.876zM30.376 256.75c-8.796-.113-14.375 0-14.375 0s5.58.113 14.375 0zM97.063 90.875c-6.478-7.35-10.813-11.938-10.813-11.938s4.162 4.772 10.813 11.938zM333.719 68.28s-.176-.063-27.314 29.376c-8.554 9.28-13.223 35.225-1.47 40.094 11.756 4.868 27.006-16.758 27.377-29.375 1.173-40.035 1.406-40.094 1.406-40.094zm-155.5.032s-.196.077 1.436 40.094c.515 12.61 15.59 34.212 27.344 29.344 11.754-4.87 7.253-30.91-1.406-40.094-27.48-29.137-27.375-29.344-27.375-29.344zm265.5 109.938s-.032.263-40.064 1.438c-3.154.09-6.9 1.12-10.625 2.78-11.17 4.987-22.43 15.748-18.78 24.563 4.87 11.755 30.844 7.117 40.125-1.436 29.445-27.14 29.344-27.344 29.344-27.344zm-375.44.03s-.075.206 29.376 27.345c9.28 8.553 35.226 13.16 40.094 1.406 3.804-9.182-8.583-20.478-20.188-25.155-3.248-1.31-6.396-2.075-9.156-2.156-40.033-1.173-40.125-1.44-40.125-1.44zm187.22 3.22c9.68-.074 19.532 1.752 29.03 5.688 38 15.74 56.024 59.345 40.283 97.343-15.74 38-59.315 56.056-97.313 40.314-37.998-15.74-56.086-59.346-40.344-97.344 11.806-28.5 39.307-45.78 68.344-46zm.5 15.72c-32.468 0-58.78 26.314-58.78 58.78 0 32.467 26.314 58.78 58.78 58.78 32.467 0 58.78-26.314 58.78-58.78 0-32.468-26.314-58.78-58.78-58.78zM122.312 297.905c-5.516.075-11.556 1.42-16.593 3.563-3.225 1.37-6.024 3.073-8.032 4.967C68.55 333.918 68.31 333.75 68.31 333.75s.113.224 40.126-1.406c12.61-.515 34.18-15.59 29.312-27.344-2.14-5.165-8.345-7.19-15.438-7.094zm266.125 0c-3.208.077-6.177.622-8.625 1.72-2.554 1.144-4.535 2.895-5.562 5.374-4.868 11.754 16.764 26.83 29.375 27.344 40.01 1.63 40.094 1.406 40.094 1.406s-.237.166-29.376-27.313c-2.295-2.164-5.63-4.104-9.438-5.562-5.133-1.965-11.12-3.097-16.47-2.97zM203.03 373.562c-1.343.054-2.71.358-4.06.907-9.645 3.92-18.913 19.3-19.314 29.155-1.63 40.01-1.437 40.063-1.437 40.063s-.11-.205 27.374-29.344c8.66-9.183 13.16-35.226 1.406-40.094-1.286-.533-2.625-.74-3.97-.688zm105.314 0c-1.148.02-2.273.263-3.375.72-11.755 4.868-7.118 30.78 1.436 40.062 27.14 29.445 27.313 29.344 27.313 29.344s-.235-.034-1.408-40.063c-.335-11.434-12.873-30.26-23.968-30.063z"></path></g></svg>`

**Comment by Delapouite** [comment]
Ok I see. It appears that InkScape (and illustrator) unfortunately does not support `rgba` in `fill` and `stroke` attributes:
https://bugs.launchpad.net/inkscape/+bug/1489187

I change the emitted SVG to rely on `fill-opacity` and `stroke-opacity` instead.

Please refresh your browser to be sure to get the new version of the Studio and it should be good.

**Comment by SilentSin** [comment]
I'm still getting a black box and black icon in Illustrator, regardless of what colour I pick for each.

Here's the code I get for changing the icon to white and box to no fill in Illustrator and saving the file:

`<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="612px" height="792px" viewBox="0 0 612 792" enable-background="new 0 0 612 792" xml:space="preserve">
<path fill="none" d="M0,90h612v612H0V90z"/>
<g transform="translate(0,0)">
	<path fill="#FFFFFF" d="M303.534,109.125c0,0-0.139,6.706,0,17.297C303.674,115.831,303.534,109.125,303.534,109.125z
		 M303.534,126.422c-0.557,42.347-5.762,149.594-43.74,165.323c-37.577,15.567-113.604-60.608-143.772-93.121
		c29.404,33.365,98.153,117.135,82.587,154.719c-15.704,37.919-120.606,43.021-162.3,43.555
		c41.692,0.533,146.591,5.675,162.3,43.594c15.777,38.086-55.115,116.851-83.82,146.574
		c29.329-28.924,106.938-100.264,145.008-84.495c37.982,15.733,43.187,121.524,43.74,163.272
		c0.541-41.755,5.674-147.623,43.703-163.272c38.614-15.889,126.996,57.614,158.79,85.729
		c-31.138-28.813-112.688-109.232-96.708-147.81c15.608-37.688,121.838-43.008,165.104-43.594
		c-43.261-0.583-149.486-5.857-165.104-43.556c-15.811-38.158,63.662-123.947,95.55-156.249
		C472.213,228.696,385.4,307.546,347.24,291.745C309.256,276.019,304.088,168.768,303.534,126.422L303.534,126.422z
		 M504.868,197.094c7.978-7.719,12.814-12.737,12.814-12.737S512.672,189.189,504.868,197.094z M574.423,396.896
		c11.242,0.151,18.452,0,18.452,0s-7.209-0.152-18.454,0H574.423z M506.027,588.298c7.188,6.646,11.654,10.57,11.654,10.57
		s-4.314-4.085-11.654-10.572V588.298L506.027,588.298z M303.534,665.843c-0.136,10.427,0,17.032,0,17.032
		S303.674,676.279,303.534,665.843z M114.785,587.064c-7.247,7.147-11.689,11.804-11.689,11.804s4.613-4.476,11.689-11.806V587.064z
		 M36.309,396.896c-10.514-0.135-17.183,0-17.183,0S25.796,397.032,36.309,396.896z M116.021,198.624
		c-7.743-8.785-12.925-14.27-12.925-14.27S108.071,190.058,116.021,198.624z M398.899,171.616c0,0-0.211-0.075-32.648,35.113
		c-10.226,11.093-15.807,42.104-1.758,47.925c14.053,5.819,32.28-20.03,32.725-35.112
		C398.618,171.688,398.898,171.617,398.899,171.616L398.899,171.616z M213.028,171.654c0,0-0.233,0.092,1.717,47.925
		c0.615,15.073,18.636,40.896,32.686,35.075c14.049-5.821,8.669-36.947-1.681-47.925
		C212.901,171.902,213.027,171.654,213.028,171.654L213.028,171.654z M530.383,303.064c0,0-0.039,0.313-47.891,1.719
		c-3.77,0.108-8.247,1.339-12.699,3.323c-13.353,5.961-26.812,18.824-22.447,29.359c5.819,14.052,36.868,8.508,47.961-1.716
		C530.503,303.309,530.383,303.065,530.383,303.064L530.383,303.064z M81.615,303.1c0,0-0.091,0.246,35.112,32.686
		c11.093,10.225,42.106,15.73,47.926,1.681c4.548-10.976-10.26-24.478-24.132-30.066c-3.882-1.566-7.645-2.48-10.943-2.577
		C81.726,303.42,81.615,303.1,81.615,303.1L81.615,303.1z M305.401,306.949c11.571-0.088,23.347,2.095,34.7,6.799
		c45.422,18.814,66.966,70.938,48.15,116.355c-18.813,45.422-70.899,67.005-116.319,48.188
		c-45.419-18.813-67.04-70.938-48.224-116.356c14.111-34.065,46.983-54.722,81.691-54.983L305.401,306.949L305.401,306.949z
		 M305.997,325.74c-38.809,0-70.26,31.453-70.26,70.26c0,38.81,31.453,70.262,70.26,70.262c38.81,0,70.262-31.453,70.262-70.262
		C376.259,357.19,344.806,325.74,305.997,325.74z M146.201,446.091c-6.595,0.09-13.813,1.696-19.834,4.259
		c-3.855,1.638-7.201,3.674-9.602,5.938c-34.828,32.852-35.115,32.649-35.115,32.649s0.136,0.269,47.963-1.68
		c15.073-0.616,40.856-18.637,35.037-32.687c-2.558-6.173-9.975-8.594-18.453-8.479L146.201,446.091z M464.303,446.091
		c-3.834,0.092-7.383,0.743-10.311,2.057c-3.053,1.367-5.42,3.46-6.646,6.423c-5.819,14.05,20.038,32.07,35.11,32.686
		c47.825,1.947,47.927,1.681,47.927,1.681s-0.284,0.198-35.114-32.647c-2.743-2.587-6.729-4.904-11.281-6.647
		c-6.136-2.349-13.292-3.701-19.687-3.55L464.303,446.091z M242.684,536.523c-1.604,0.064-3.239,0.429-4.853,1.085
		c-11.528,4.687-22.606,23.069-23.086,34.849c-1.948,47.825-1.719,47.889-1.719,47.889s-0.132-0.245,32.722-35.075
		c10.351-10.977,15.729-42.104,1.681-47.925C245.891,536.709,244.291,536.462,242.684,536.523L242.684,536.523z M368.568,536.523
		c-1.373,0.024-2.718,0.314-4.034,0.861c-14.052,5.817-8.509,36.791,1.717,47.887c32.44,35.195,32.646,35.075,32.646,35.075
		s-0.28-0.041-1.683-47.888c-0.4-13.668-15.389-36.172-28.649-35.937L368.568,536.523L368.568,536.523z"/>
</g>
</svg>`

**Comment by SilentSin** [comment]
I cleared my cache and it works now.
