### ISSUE TITLE
ideas : multiple line on text and draw area

### ISSUE THREAD

**Issue by catafest** [game-icons/icons#453]
1. why cannot add multiple line on text add to icon?
2. why cannot have a draw area for simple badge and then to be add to icons?

**Comment by Delapouite** [comment]
Thanks for your suggestions.

You can now add multiline text.
The draw area is getting quite complicated and a bit out of scope. This tool should remain simple. Real vector editor like InkScape or Illustrator should be used for more advanced tasks.
