### ISSUE TITLE
Cannot make icons transparent

### ISSUE THREAD

**Issue by novasuecia** [game-icons/icons#457]
I am no longer able to make icons transparent. There used to be a button to the right but it doesn't appear any more. I've tried with the web browsers Safari 11.0.2, Firefox 57.0.3 and Chrome 63.0.3239.84 at Mac OS X 10.13.2.

<img width="1200" alt="transparent" src="https://user-images.githubusercontent.com/34273699/34439305-35ffaf10-ecad-11e7-836c-97b715de85a9.png">

**Comment by Delapouite** [comment]
Hello.

Each time there's a color picker, the round black disc on the screenshot, you can choose the alpha property of the color which corresponds to the transparency.

So you can make the background transparent but setting the alpha to 0.
