### ISSUE TITLE
Request/Idea: Steam Blast

### ISSUE THREAD

**Issue by ryan-mcguire** [game-icons/icons#459]
I'm looking for an icon of a high-pressure blast of steam, like what might come from a train whistle (but without the whistle) or an espresso maker.  I'm picturing something like Sinusoidal Beam (without the sine wave) or Fragmented Meteor but with a cloud of steam in the lower right.

**Comment by Delapouite** [comment]
Hi. Here comes a steam blast http://game-icons.net/delapouite/originals/steam-blast.html
