### ISSUE TITLE
Icons needed Objective

### ISSUE THREAD

**Issue by UncleFred** [game-icons/icons#470]
Hi again!

This one request is a bit of a challenge. I don't know how you would go about styling this one.

Looking for an icon that would communicate the word "objectives" in a stats system. Typically, these are levers, buttons, or rally point locations the player has to go.

Nothing like this exists it seems. Would be very interested to see what you could come up with.

**Comment by Delapouite** [comment]
A flag objective has been added https://game-icons.net/1x1/delapouite/flag-objective.html
