### ISSUE TITLE
Request: Rounded Square Backgrounds

### ISSUE THREAD

**Issue by eugirdor** [game-icons/icons#475]
Being able to choose a square with rounded corners for the background shape, much like how the backgrounds look on the website.  Bonus if the corner radius is adjustable.

**Comment by Delapouite** [comment]
Hello. A rounded square has been added. (you may have to refresh your browsert to get it). For now, the radius is hardcoded to 32px. An input may be added in the future. For now, you can tweak this value in the exported SVG by changing the value of `rx` and `ry` on the `rect`

**Comment by eugirdor** [comment]
@Delapouite Your turnaround time is ridiculous.  Bravo 👏

**Comment by Delapouite** [comment]
The radius can now be adjusted.
