### ISSUE TITLE
Request: private, corporal and maybe other badges

### ISSUE THREAD

**Issue by erikem** [game-icons/icons#476]
Please add "private" and "corporal" badges as well as probably some other military badges because they are perfect for showing up improved versions of the same skill/unit in cases where I want to avoid using explicit +1, +2, +3, etc. texts

**Comment by Delapouite** [comment]
Hi.
There's already the `private`, `corporal`, `sergeant` trio on this page http://game-icons.net/tags/rank.html
Do you have something else in mind?

**Comment by erikem** [comment]
I meant badges - small circle-shaped icons we can put on top of the initial icon. These ones: http://game-icons.net/badges.html

**Comment by erikem** [comment]
Actually it would be cool if we could put any existing icon as a badge

**Comment by Delapouite** [comment]
The private and corporal badges have been added.
