### ISSUE TITLE
Musical keyboard

### ISSUE THREAD

**Issue by derpleguy** [game-icons/icons#482]
hello, i just want to suggest a musical keyboard icon, specifically something that looks like a Casio SK-5
picture: https://medias.audiofanzine.com/images/normal/casio-sk-5-879562.jpg

**Comment by Delapouite** [comment]
A musical keyboard is ready https://game-icons.net/delapouite/originals/musical-keyboard.html

It has no black keys, the stroke width is to high to add them correctly.
