### ISSUE TITLE
Sabre & Pistol

### ISSUE THREAD

**Issue by Eremiell** [game-icons/icons#485]
It would be great if a combined sabre/pistol icon could be added. Something like one of [those](http://game-icons.net/lorc/originals/crossed-sabres.html) with one of [those](http://game-icons.net/lorc/originals/crossed-pistols.html).

I often wanna represent some late medieval/early modern age-esque era weapons as a general category and have to go with either swords or guns or try to put together something myself with my limited graphical skills.

Thanks for consideration.

**Comment by Delapouite** [comment]
Hi. Here it comes : http://game-icons.net/delapouite/originals/saber-and-pistol.html
