### ISSUE TITLE
Download one svg file

### ISSUE THREAD

**Issue by EntityB** [game-icons/icons#490]
Hey,

could it be possible to download all icons as one svg file instead of many svg files?

**Comment by Delapouite** [comment]
Hi. How this giant SVG file be structured ?

**Comment by EntityB** [comment]
I find this set of icons as very handy in making prototypes. But manipulation with each seperate file is not very user friendly. 

I could use file with vector masks in photoshop. So I could move vector masks on custom layers, resize them and apply various blending options. While I'm writing this I realize it could be also .csh file (custom shapes to photoshop). Do you think this would be possible?

**Comment by EntityB** [comment]
Hey there, 
I was not hesitating and I managed to do a port of all of your 3209 icons to one single .csh file. I put all details into my repo here:
https://github.com/EntityB/game-icons

Here is a preview in photoshop
[![Photoshop CS5 3209 shapes preview](https://github.com/EntityB/game-icons/raw/master/doc/preview.jpg)](https://github.com/EntityB/game-icons/raw/master/doc/preview.jpg)

Do whatever you need with this issue, personally for me, this is resolved. 
PS: thanks for your fast reply and interest

**Comment by Delapouite** [comment]
Thanks a lot! I've tweeted it to spread the love https://twitter.com/GameIcons/status/971759674356846592
