### ISSUE TITLE
Break apart can't be used with stroke?

### ISSUE THREAD

**Issue by ColtonCGraham** [game-icons/icons#491]
Having trouble breaking apart an icon and then using the stroke out-liner. Seems to just make the whole icon disappear.

**Comment by Delapouite** [comment]
I was not able to reproduce this bug.
Here is an example with different stroke color applied to various part of the Scarab after it has been broken apart.

![image](https://user-images.githubusercontent.com/39315/62717258-dacc4880-ba03-11e9-9263-7c19d5e1f2a8.png)
https://game-icons.net/1x1/lorc/scarab-beetle.html

Which icon caused you trouble in particular?
