### ISSUE TITLE
D2 dice or coin flip

### ISSUE THREAD

**Issue by DFreds** [game-icons/icons#492]
Example d2 dice: https://goo.gl/images/M2VTWS

A coin flip looking icon would also work.

**Comment by otakuto** [comment]
404

**Comment by DFreds** [comment]
https://www.google.com/search?q=d2+dice

Really any picture there

**Comment by Delapouite** [comment]
A coin flip is ready: https://game-icons.net/1x1/caro-asercion/coinflip.html
