### ISSUE TITLE
No background

### ISSUE THREAD

**Issue by EdBailey** [game-icons/icons#503]
It would be useful to be able to get the icons with no background. I can make the background transparent, but this leaves extra junk in the file that I would prefer not to have. Obviously I can manually remove this and it's not much work, but it might be a nice feature to be able to remove the background entirely.

Thanks

**Comment by Delapouite** [comment]
Hello. The option has been added in a dropdown. Background > Type > none.

**Comment by EdBailey** [comment]
Thankyou so much :D
