### ISSUE TITLE
I am the fan of this project. I got few question about this.

### ISSUE THREAD

**Issue by LuckyTyga** [game-icons/icons#520]
1，What tools do you use for painting?
2，What is the style of this type of painting?
3，Is there a tutorial for this style painting?
4，Can you teach me painting this style?

**Comment by Delapouite** [comment]
Hello 

1 - https://inkscape.org/en/
2 - Vector design
3 - Probably somewhere on youtube
4 - No time, sorry.

**Comment by LuckyTyga** [comment]
thx
