### ISSUE TITLE
Female Armor

### ISSUE THREAD

**Issue by onkarjit** [game-icons/icons#527]
Most of the armor, is male armor. It would be nice if female armor could be added as well.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/26631593/43677411-d5ffd742-9801-11e8-97b2-d1d685351100.png">

So perhaps a female breastplate, greaves, boots, gloves and helm would be nice.

**Comment by Delapouite** [comment]
You're right. Here's a piece of armor suited for female https://game-icons.net/delapouite/originals/leather-armor.html

Also a sleeveless top has just been added: https://game-icons.net/delapouite/originals/sleeveless-top.html

**Comment by Delapouite** [comment]
Cape armor: https://game-icons.net/1x1/delapouite/cape-armor.html

**Comment by Delapouite** [comment]
A travel dress https://game-icons.net/1x1/delapouite/travel-dress.html

**Comment by Delapouite** [comment]
A cape: https://game-icons.net/1x1/delapouite/basset-hound-head.html
