### ISSUE TITLE
Hackerdom Icon / Conway's Game of Life Glider

### ISSUE THREAD

**Issue by greysondn** [game-icons/icons#531]
https://en.wikipedia.org/wiki/Glider_(Conway%27s_Life)

A _relatively_ definitive text on the subject is here:
http://www.catb.org/hacker-emblem/

**Comment by Delapouite** [comment]
Good idea! Here it is https://game-icons.net/delapouite/originals/conway-life-glider.html

**Comment by greysondn** [comment]
Thank you very much :D
