### ISSUE TITLE
Earrings

### ISSUE THREAD

**Issue by Slexom** [game-icons/icons#540]
First of all, thank you :D
I've decided to finally add earrings, last missing equipment piece, to my little project. I've looked for them but there are no earrings in the icon list. Is possible to add some? Or there is some icon I can adapt?

**Comment by Delapouite** [comment]
Another pair of earrings https://game-icons.net/1x1/delapouite/drop-earrings.html

**Comment by Delapouite** [comment]
More earrings:

https://game-icons.net/1x1/delapouite/crystal-earrings.html
https://game-icons.net/1x1/delapouite/heart-earrings.html
https://game-icons.net/1x1/delapouite/pearl-earring.html
