### ISSUE TITLE
Game Icons used for Sci-Fi card game RPG

### ISSUE THREAD

**Issue by necrorat** [game-icons/icons#541]
I remember reading I should post here if icons are used for a game.  I have a game that is about to be released late October 2018 that used a pretty big chunk of icons.  Link to game-icons.net and appropriate artists have been credited.  Game is called Spaceship Architect and can be found here: http://tinyurl.com/drivethrurpg26LP

I can't thank game-icons enough!

**Comment by Delapouite** [comment]
Thanks for sharing! I'm closing this issue as not actionable.
