### ISSUE TITLE
Approved / Confirmed icon

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [game-icons/icons#549]
For GUI like the Cancel icon (https://game-icons.net/sbed/originals/cancel.html) but with a check inside? or a unchecked/checked box?

**Comment by Delapouite** [comment]
Not quite there yet, but here's a choice icon with check and cross https://game-icons.net/1x1/delapouite/choice.html

**Comment by Delapouite** [comment]
The confirmed icon has been added http://game-icons.test/1x1/delapouite/confirmed.html
