### ISSUE TITLE
modern guns

### ISSUE THREAD

**Issue by Delapouite** [game-icons/icons#55]
http://forum.game-icons.net/request-modern-guns

**Comment by Delapouite** [comment]
http://game-icons.net/delapouite/originals/uzi.html

**Comment by Delapouite** [comment]
http://game-icons.net/skoll/originals/luger.html

**Comment by Delapouite** [comment]
A famas has been added http://game-icons.net/skoll/originals/famas.html

**Comment by Delapouite** [comment]
http://game-icons.net/skoll/originals/steyr-aug.html

**Comment by ishmadrad** [comment]
I export the Famas in SVG. It's "broken", it misses the handle etc. Usually I can ungroup them in Inkscape so I can tinker with them, but this one seems weird.

**Comment by Delapouite** [comment]
It's a bug in Inkscape which have difficulties handling SVG where a space is missing before negative numbers. It should be fixed in their next release.

Meanwhile, a lee enfield has been released : http://game-icons.net/skoll/originals/lee-enfield.html

**Comment by Delapouite** [comment]
Lots of guns will be added in the following releases thanks to skoll. Follow the gun tags to see them coming : http://game-icons.net/tags/gun.html
