### ISSUE TITLE
Reset position of foreground element without full reset

### ISSUE THREAD

**Issue by jonathan-wideman** [game-icons/icons#567]
In studio, after dragging the foreground element, it would be great to be able to reset its position  without resetting the rest of the icon settings.

**Comment by Delapouite** [comment]
![image](https://user-images.githubusercontent.com/39315/62247997-59fbc400-b3e7-11e9-9963-7dfc925db9dd.png)

A new `Position` section is now available for the Foreground (you may need to refresh you browser cache).
If you set the values of `x` and `y` to `0`, it resets the initial position.
