### ISSUE TITLE
Racoon

### ISSUE THREAD

**Issue by kendallroth** [game-icons/icons#569]

**Comment by deuxlames** [comment]
Would this be ok ?
![racoon-face](https://user-images.githubusercontent.com/33799733/54881072-3f6b7a00-4e4c-11e9-89d8-72519deb0ad9.png)

**Comment by kendallroth** [comment]
Hm, my only question would be whether it matches the overall style of the other icons on the site (seems a touch busy)? But I don't know who decides that?

**Comment by Delapouite** [comment]
Here comes a raccoon https://game-icons.net/1x1/delapouite/raccoon-head.html
