### ISSUE TITLE
Request: Legs

### ISSUE THREAD

**Issue by emeneghim** [game-icons/icons#575]
Hey, I'm currently coding an RPG for a school project and I need some icons for equipment on the item list bag, and the only icons that I'm having trouble to find is legs, so I would like to request a Muscular Leg and maybe an Armored Leg (I can see there is one but it is not showing?).

Thank you in advance, and it is a very nice work that you do.

**Comment by Delapouite** [comment]
A leg https://game-icons.net/1x1/delapouite/leg.html and a knee cap have been added https://game-icons.net/1x1/delapouite/knee-cap.html
