### ISSUE TITLE
Idea: Icons delivered as a font

### ISSUE THREAD

**Issue by nukeop** [game-icons/icons#579]
I might have missed it, but I believe that icons are currently only distributed in svg form. It would be cool if there was a web font containing them too. Unicode has plenty of room and I think I could at least build a font with all currently available fonts, or maybe make a script that could run on CI and rebuild the font on every push. Any interest?

**Comment by Delapouite** [comment]
Hello.

A font is already available as a side project: https://seiyria.com/gameicons-font/
