### ISSUE TITLE
Deer, Rabbit, Boar

### ISSUE THREAD

**Issue by Istencsaszar66** [game-icons/icons#586]
Please create a deer, rabbit and boar icon with the same style. Best would be a simple, full-body icon.

**Comment by Delapouite** [comment]
A rabbit is already available https://game-icons.net/1x1/delapouite/rabbit.html

**Comment by Istencsaszar66** [comment]
yes, i know. And that one is just pefect...then could u create a deer and a boar in the same style?

**Comment by Delapouite** [comment]
A deer: https://game-icons.net/1x1/caro-asercion/deer.html
A boar: https://game-icons.net/1x1/caro-asercion/boar.html
