### ISSUE TITLE
Site not accessible via `www` subdomain.

### ISSUE THREAD

**Issue by follower** [game-icons/icons#587]
While I can access the site via these URLs:

 * https://game-icons.net/
 * http://game-icons.net/

I can't access the site from these URLs which include the `www` subdomain prefix:

* https://www.game-icons.net/
* http://www.game-icons.net/

I discovered this because this page uses a link that includes the `www` subdomain:

* https://help.thegamecrafter.com/article/29-art-resources

Checking via the Google provided DNS server:

```
$ host game-icons.net 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

game-icons.net has address 151.80.46.163

$ host www.game-icons.net 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

Host www.game-icons.net not found: 3(NXDOMAIN)
```

**Comment by Delapouite** [comment]
Thanks! Should be good now.
