### ISSUE TITLE
$100 for android CHESS MOD (coder keep all app rev) with 3 advertisments

### ISSUE THREAD

**Issue by Punkroku** [game-icons/icons#588]
$100 for android chess mod with an advertisment to openInvent.club

Any1?? Want to make a kickstarter or gofundme? Mine are all censored see tiny.cc/rights and tiny.cc/rights1 seeking freedom of speech in court. Public courts and Internet Access (Constitutional Right to Assemble in peace also desired. See tiny.cc/deniedpapers for a 9th circuit appeal where a man is denied legal paperwork even on court appeal.)

The chess mods include life [vampire] chess object avoid opponents color. Checkers = Life.
The 10X10 expansion pack will break most AI. See shirt design at tiny.cc/ramaclubart possible fundraiser idea EverChesst - Expansion Pack
Excalibur Chess need to add icon for king riding on horse.
Samurai Chess needs all new are pieces for chess: Ninja [knight] Pagoda [Rook] Emperor [King] Empress [Queen] Samurai [Pawn] Suma [2 space fat pawn] I forgot what I called the Bishop I think it was A Fanner type Guard that is from Chinese Chess. See link below.

Hey all would you like to modify chess icons for Samurai Chess and Excalibur Chess.
Samurai Chess renames all pieces as stated at tiny.cc/samuraichess
It adds a piece called Suma Wrestler [Pawn] that is two icons fat. See symbol.com for proposed openInvent suma pawn.

PS if anyone is competent enough to code an Android App I am fine with them keeping all ad revenue but I would love 3 start up splash promoting the trademarks openInvent and Bitsfit Rama Club. I have art and can whip up a BitInvader Sound Jingle using chiptune like sounds and LMMS.

For free stickers (tiny.cc/oisticker) write:
openInvent.club
c/o Ember Autumn Rose Leona
250 S Lyon Ave Ste E108
Hemet CA 92543

**Comment by Punkroku** [comment]
https://www.symbols.com/symbol/black-suma-pawn---samurai-chess

**Comment by Punkroku** [comment]
Other symbols https://www.symbols.com/user/27118

**Comment by Delapouite** [comment]
Please, keep your spam out of my issue tracker.

**Comment by Punkroku** [comment]
Ok it was a legitimate job post. Sorry for the blunt approach [espeak "et tu B*"]

It seems that my emails get "lost" you can snail mail me at the address below and I will reply with sticker gifts.(tiny.cc/oisticker)
Ember AR Leona
250 S. Lyon Ave Ste E 108
Hemet, CA 92543

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
