### ISSUE TITLE
Request: Bundle of grain

### ISSUE THREAD

**Issue by SpencerDub** [game-icons/icons#589]
I'd like to request a bundle of grain tied with a rope or string, similar to a sheaf of wheat. An example of what I mean can be found [here](https://thenounproject.com/search/?q=wheat%20sheaf&i=1416198).

This would be useful for grain or wheat as a discrete resource, whereas the [existing wheat icon](https://game-icons.net/1x1/lorc/wheat.html) seems better suited to fields of grain.

**Comment by Delapouite** [comment]
Thanks for the idea. I'll try to add something in the line of https://game-icons.net/1x1/delapouite/herbs-bundle.html

**Comment by SpencerDub** [comment]
That would be great, thanks!

**Comment by Delapouite** [comment]
A bundle of grain is ready https://game-icons.net/1x1/delapouite/grain-bundle.html
