### ISSUE TITLE
Request: wire

### ISSUE THREAD

**Issue by otakuto** [game-icons/icons#594]
https://images.app.goo.gl/ZxRecMveffV8zfgR7

Thank you.

**Comment by Delapouite** [comment]
Almost https://game-icons.net/1x1/delapouite/sewing-string.html

**Comment by otakuto** [comment]
Would you remove a needle?

**Comment by Delapouite** [comment]
Here it comes https://game-icons.net/1x1/delapouite/wire-coil.html
