### ISSUE TITLE
Request: Frozen Man

### ISSUE THREAD

**Issue by Kingmiami** [game-icons/icons#601]
We have a man on fire, a man electrocuted, but no man frozen in ice... that I can find at least.

That aside, awesome website!

https://thumbs.dreamstime.com/z/man-summer-clothes-frozen-ice-cube-conceptual-image-107967541.jpg

**Comment by Delapouite** [comment]
Refs:

man on fire: https://game-icons.net/1x1/lorc/fire-silhouette.html
electrocuted man: https://game-icons.net/1x1/lorc/deadly-strike.html

**Comment by Delapouite** [comment]
A frozen body https://game-icons.net/1x1/delapouite/frozen-body.html
