### ISSUE TITLE
Request: Foundry

### ISSUE THREAD

**Issue by mswebmaster** [game-icons/icons#602]
https://images.app.goo.gl/3PEVbBKoppbQQukZ8

**Comment by Delapouite** [comment]
Related: https://github.com/game-icons/icons/issues/399

**Comment by Delapouite** [comment]
A few foundry related icons are now available:

- https://game-icons.net/1x1/delapouite/foundry-bucket.html
- https://game-icons.net/1x1/delapouite/melting-metal.html
- https://game-icons.net/1x1/delapouite/furnace.html
