### ISSUE TITLE
Request: Logic Gate

### ISSUE THREAD

**Issue by otakuto** [game-icons/icons#605]
https://en.wikipedia.org/wiki/Logic_gate#Symbols

**Comment by Septatrix** [comment]
These symbols are all licensed under CC0 if I saw correctly. If they fit the style you may be able to include them directly.

**Comment by Delapouite** [comment]
They'll be available next week

**Comment by Delapouite** [comment]
Logic gates are available on this page https://game-icons.net/tags/electronic.html
