### ISSUE TITLE
Request: Reset Studio Editor

### ISSUE THREAD

**Issue by Septatrix** [game-icons/icons#608]
I'd like to have a button at the bottom of the editor to reset the icon to the initial state.
Often I find myself reopening the page or a new icon but wanting to get the original unedited icon. However the editor state is stored in localStorage.

Currently I resort to executing `localStorage.removeItem('game-icons'); location.reload();` in the console but this is far from ideal. Implementing this shouldn't be to difficult as we only need to revert the current editor data to normal and update the internal objects to reflect the data as opposed to reloading the whole window.

**Comment by Delapouite** [comment]
Hello. There's already a reset button: 

![image](https://user-images.githubusercontent.com/39315/65817132-e833d100-e203-11e9-9d94-00aa09a4eacb.png)

Does it work as you expect?

**Comment by Delapouite** [comment]
A new version of the studio has been released. You can now reset the background, the foreground, the text or the badge independently. There's a reset button at the bottom of each section.

**Comment by Septatrix** [comment]
Yes, this works exactly as imagined it. Thanks!
