### ISSUE TITLE
Add Percentage Badge?

### ISSUE THREAD

**Issue by StevenBuwing** [game-icons/icons#610]
Hello Authors of Game-Icons.net

I, personally, missed a "percentage"-badge (%) to put on your icons via the badge-option in 'Studio'.
Do you think it is an appropiate addition to the already existing badges?

I would really like to use it for a 'chance' icon.

Your work is very much appreciated and a real gold mine for new developers.

**Comment by StevenBuwing** [comment]
Thank you for labeling @Delapouite 
I managed to forget it myself.

**Comment by StevenBuwing** [comment]
I'm actually very sorry to have made that request.
I just realized I could overlay a text with a '%' onto the 'blank'-badge, thus creating the requesteded percentage-badge with the help of Studio already.
I just didn't saw it at first!

Thanks nonetheless :)

**Comment by Delapouite** [comment]
Yes, you can combine the text + the blank badge.
A percentage badge has been added to make this process easier: https://game-icons.net/badges.html (other ones as well)
