### ISSUE TITLE
Vibrating phone / Vibration enabled

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [game-icons/icons#616]
I want to suggest a new icon for a vibrating phone (phone with some lines around it).
Like a combination of 
https://game-icons.net/1x1/skoll/smartphone.html
and
https://game-icons.net/1x1/lorc/aerial-signal.html
(or https://game-icons.net/1x1/lorc/vibrating-ball.html )

**Comment by Delapouite** [comment]
https://game-icons.net/1x1/delapouite/vibrating-smartphone.html
