### ISSUE TITLE
useless line in cowled icon

### ISSUE THREAD

**Issue by DreadKnight** [game-icons/icons#618]
The "Cowled" icon has a pointless line at the bottom when using a stroke of 4.
https://game-icons.net/1x1/lorc/cowled.html

**Comment by Delapouite** [comment]
True. Some out of bound vertices have not been erased correctly while exporting.

**Comment by Delapouite** [comment]
Should be fixed now.

**Comment by DreadKnight** [comment]
@Delapouite Indeed, looks good now and a 50% size decrease, woot! Well done! :+1:
