### ISSUE TITLE
Display issue in the website search page

### ISSUE THREAD

**Issue by BertrandAlexandre** [game-icons/icons#624]
Hello,

In the search page, it seems that there is a display error in the description of logos with HTML link ("Turtle shell", "Trefoil shuriken", ...).
The content of the description is displayed as text and not as HTML.
Thus the link contained in the description is not correctly displayed:
https://game-icons.net/search.html?q=turtle%20shell
https://game-icons.net/search.html?q=trefoil%20shuriken

**Comment by Delapouite** [comment]
Thanks for the report. Should be fixed now.
