### ISSUE TITLE
Generate unique IDs when exporting SVGs

### ISSUE THREAD

**Issue by arabold** [game-icons/icons#628]
It would be great if downloading SVGs via the website would generate unique IDs, e.g. for gradients. If I export multiple SVGs, each with a different gradient, they all use the same IDs `"gradient-1"`, `"gradient-2"`, etc. This causes problems when displaying multiple SVGs on a single HTML page as the IDs conflicts and the images are rendered with wrong colors. I have to manually edit each SVG file and use a unique ID instead.

A simple but effective fix would be to generate unique IDs when exporting the icons. The IDs could be completely random, e.g. by using a UUID.

**Comment by Delapouite** [comment]
Hello.

The studio has been updated today and gradients should have unique ids:

![image](https://user-images.githubusercontent.com/39315/99193415-05fe2580-2779-11eb-8864-b8ead74027fd.png)
