### ISSUE TITLE
Dimetrodon

### ISSUE THREAD

**Issue by evanrinehart** [game-icons/icons#629]
The text reads

> A big lizard with a massive crest on its back. This dinosaur is not too distant from current Komodo dragons.

and it has the tag "reptile".

According the current wikipedia this iconic animal was neither a dinosaur (being extinct millions of years before the first dinosaurs) nor a lizard, nor even an unambiguous reptile. It was a weird offshoot toward evolution of mammals though not ending up as an ancestor of modern mammals. Ignore this issue or perhaps make a pop culture reference to it in the flavor text!

**Comment by Delapouite** [comment]
Thanks for this precision! I had no idea that this mighty beast was its own species. I'll definitely add this in the icon description.

**Comment by Delapouite** [comment]
The description has been adjusted. Thanks.
