### ISSUE TITLE
Bug: Logic Gate NOT icon is incorrect

### ISSUE THREAD

**Issue by ACG8** [game-icons/icons#637]
The image used for "Logic Gate NOT Icon"  is not correct; a NOT gate has only one input, but the image has two. There should be only one wire leading in on the left side of the gate.

https://game-icons.net/1x1/delapouite/logic-gate-not.html
https://en.wikipedia.org/wiki/Inverter_(logic_gate)

**Comment by Delapouite** [comment]
Thanks for your contributions. It's been fixed!
