### ISSUE TITLE
A wall of fire

### ISSUE THREAD

**Issue by aloisdg** [game-icons/icons#640]
I would love to have a fire wall. They are lot of game using a spell producing a firewall. I have in mind something akin to [fire-wave](https://game-icons.net/1x1/lorc/fire-wave.html) and [flame-tunnel](https://game-icons.net/1x1/lorc/flame-tunnel.html), but with a constant height.

wave:
![wave](https://user-images.githubusercontent.com/3449303/75993013-26db5f00-5ef9-11ea-8dd0-948662dfe85a.png)

tunnel:
![tunnel](https://user-images.githubusercontent.com/3449303/75993010-25aa3200-5ef9-11ea-9a40-d92351101547.png)

wall:
![wall](https://user-images.githubusercontent.com/3449303/75993012-2642c880-5ef9-11ea-81d0-f5df39e95c4e.png)

**Comment by Delapouite** [comment]
A wall of fire is ready: https://game-icons.net/1x1/delapouite/firewall.html

**Comment by aloisdg** [comment]
Awesome thank you !
