### ISSUE TITLE
Galaxy icon

### ISSUE THREAD

**Issue by MilanStaffehl** [game-icons/icons#643]
A galaxy icon would be nice, ideally a spiral galaxy to represent the milky way. *Star Swirl* is a bit too cartoony for most cases.

**Comment by aloisdg** [comment]
https://game-icons.net/1x1/lorc/star-swirl.html

**Comment by Delapouite** [comment]
A galaxy has been added https://game-icons.net/1x1/delapouite/galaxy.html
