### ISSUE TITLE
Icon of Chakram

### ISSUE THREAD

**Issue by aloisdg** [game-icons/icons#644]
Hello,

Chakram are old throwing weapons. From [wiki](https://en.wikipedia.org/wiki/Chakram),

> The chakram (Tamil: chakkaram; Sanskrit: chakram; Punjabi: chakkar; Malay: cakeram) is a throwing weapon from the Indian subcontinent. It is circular with a sharpened outer edge and a diameter of 12–30 centimetres (4.7–11.8 in). It is also known as chalikar meaning "circle", and was sometimes referred to in English writings as a "war-quoit". The Chakram is primarily a throwing weapon but can also be used hand-to-hand. A smaller variant called chakri was worn on the wrist. A related weapon is the chakri dang, a bamboo staff with a chakri attached at one end. 

A Xena style chakram would fit the need:
![example](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/eed3468f-28cc-4d56-9614-ea9a607b6e2c/d79qiw9-2e3a9193-e2c4-443c-9fd6-d15dc48566bb.png/v1/fill/w_1024,h_1024,q_75,strp/chakram_from_xena__warrior_princess_by_karynrh-d79qiw9.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl0sIm9iaiI6W1t7InBhdGgiOiIvZi9lZWQzNDY4Zi0yOGNjLTRkNTYtOTYxNC1lYTlhNjA3YjZlMmMvZDc5cWl3OS0yZTNhOTE5My1lMmM0LTQ0M2MtOWZkNi1kMTVkYzQ4NTY2YmIucG5nIiwid2lkdGgiOiI8PTEwMjQiLCJoZWlnaHQiOiI8PTEwMjQifV1dfQ.3f7wTXj-gTMrpnNNyz6336SD9b66eqJ_RiaizV8S2mk)

![image](https://user-images.githubusercontent.com/3449303/76762080-e8636100-6790-11ea-9c62-817354ee1ba2.png)

Thank you!

**Comment by Delapouite** [comment]
Hi, a chakram icon has been published https://game-icons.net/1x1/delapouite/chakram.html

**Comment by aloisdg** [comment]
Perfect! You rocks!
