### ISSUE TITLE
Bug: search bar non-functional, Google auto-complete search not working

### ISSUE THREAD

**Issue by chrisbacke** [game-icons/icons#649]
The search bar at the top of the page is totally non-functional. No 'submit' button, hitting enter doesn't work... The site used to have a Google auto-complete option (which I LOVED), but now that doesn't appear on the site...

Bug(?) appears in both latest versions of Chrome and Firefox. I've ensured all ad-blocking extensions are turned off, still no dice.

(Sorry if I'm not following the proper format here - don't spend much time here on Github!)

**Comment by Delapouite** [comment]
This widget is provided "as-is" by Algolia, so for now it's currently out of my control. I agree that it's not that keyboard-friendly but you can circumvent most problems by highlighting the result you need with the arrow keys and then hit return.

**Comment by chrisbacke** [comment]
OK, think I've solved it. Seems NordVPN, on at least two American IP addresses, prevents the Algolia widget from loading. The website substitutes in a generic search bar instead, but is (probably) not connected to any actual form submit activity. Turned off the VPN and the site loads perfectly.

This is what I was seeing on desktop — just a basic search bar - 
![2020-03-23 18_12_55-Microsoft Edge](https://user-images.githubusercontent.com/59960097/77343460-fb96a380-6d31-11ea-8001-95e0e078c5a3.jpg)

Going to close this here — if others report the same issue, ask them to disconnect from their VPN and force refresh =) Thanks for a great site.
