### ISSUE TITLE
desk lamp file needs clean-up

### ISSUE THREAD

**Issue by DreadKnight** [game-icons/icons#660]
Desk lamp looks kinda bad with 4px outline, crappy corner settings and some spot on the right side.
https://game-icons.net/1x1/lorc/desk-lamp.html

**Comment by Delapouite** [comment]
Thanks. The desk lamp is icon is fixed. https://github.com/game-icons/icons/commit/86d5b6efe9fdb0832a3a9659beff135eb3d58cbd
