### ISSUE TITLE
Jelly

### ISSUE THREAD

**Issue by HeavenlyDog** [game-icons/icons#661]
Cheers!

I haven't written or asked for any icon for years. I am designing a board game and I would need a jelly icon. It's possible?
Greetings from Annonay, France.

**Comment by Delapouite** [comment]
Hi.

Do you mean this kind of jelly?

![image](https://user-images.githubusercontent.com/39315/82224231-e5692600-9923-11ea-9791-f2091f481577.png)

**Comment by HeavenlyDog** [comment]
Oui, just ça!

**Comment by Delapouite** [comment]
Here comes jelly https://game-icons.net/1x1/delapouite/jelly.html
