### ISSUE TITLE
Badges for exclamation mark and building

### ISSUE THREAD

**Issue by andbruu** [game-icons/icons#670]
Hi
I would love to have these two badges for a game project. A simple house silhuet for the building badge would be nice.

As this is my first request, I will use the oppotunity to thank everyone making these icons. Its a vital resource for a would be game designer like me.

I am unsure how to add tags to posts, but this is a request.

**Comment by Delapouite** [comment]
Hi. 3 new badges have been added:
- exclamation mark
- question mark
- building

https://game-icons.net/badges.html
