### ISSUE TITLE
See all icons

### ISSUE THREAD

**Issue by bodamat** [game-icons/icons#671]
Can please add page, where I can see all icons added to site. Thank you!

**Comment by Delapouite** [comment]
Hello. There's this page listing the latest additions to the collection: https://game-icons.net/recent.html

**Comment by bodamat** [comment]
Yes, but not all icons on server!

**Comment by Delapouite** [comment]
Such a page would be way too demanding on bandwidth as we're approaching the 4000 icons mark.

**Comment by bodamat** [comment]
You can turn the pages. So it will be a bit demanding, but adds great convenience. Something has to be sacrificed.
