### ISSUE TITLE
Some icons unecessarily use shapePadding property which is still in draft

### ISSUE THREAD

**Issue by posita** [game-icons/icons#676]
The SVG archive has a few glitches that make batch processing difficult by tools like [SVGR](https://react-svgr.com/docs/cli/).

[`delapouite/jumping-rope`](https://game-icons.net/icons/000000/transparent/1x1/delapouite/jumping-rope.svg) and [`delapouite/wood-beam.svg`](https://game-icons.net/icons/000000/transparent/1x1/delapouite/wood-beam.svg) both include `shapePadding: 0`, which fails translation to CSS in tools that are not aware of [CSS Shapes 2 Draft](https://drafts.csswg.org/css-shapes-2/) properties (including the [`csstype` Typescript package](https://github.com/frenic/csstype), which currently only supports CSS Shapes 1; see frenic/csstype#101). With those icons, the property is set to `0` in both cases, meaning it likely has no effect, and narrows compatibility of the icon. I suggest removing it.

**Comment by posita** [comment]
I'm pretty sure this can be classified as a `bug`. In any event #682 provides a fix.

**Comment by Delapouite** [comment]
Thanks. You're right, `style` attributes should not have been found in the final svg files. It should be fixed now.
