### ISSUE TITLE
lorc's pawprint and paw-print don't survive renaming conventions well

### ISSUE THREAD

**Issue by posita** [game-icons/icons#677]
[`lorc/paw-print.svg`](https://game-icons.net/icons/000000/transparent/1x1/lorc/paw-print.svg) and [`lorc/pawprint.svg`](https://game-icons.net/icons/000000/transparent/1x1/lorc/pawprint.svg) are similarly named. Tools that attempt to derive different filenames from those can result in conflicts. For example, when batch processing via [SVGR](https://react-svgr.com/docs/cli/), those files result in `PawPrint.js` and `Pawprint.js`, respectively. On case-insensitive filesystems (the default on Mac OS and Windows), one ends up overwriting the other. Consider renaming them to so these types of clashes are avoided.

For guidance, disambiguating using numbers already enjoys convention, even in `lorc`'s own contributions. Consider:

- [`dna1.svg`](https://game-icons.net/icons/000000/transparent/1x1/lorc/dna1.svg) vs. [`dna2.svg`](https://game-icons.net/icons/000000/transparent/1x1/lorc/dna2.svg)
- [`snowflake-1.svg`](https://game-icons.net/icons/000000/transparent/1x1/lorc/snowflake-1.svg) vs. [`snowflake-2.svg`](https://game-icons.net/icons/000000/transparent/1x1/lorc/snowflake-2.svg)

**Comment by posita** [comment]
Fixed in #683.

**Comment by Delapouite** [comment]
Thanks. It's been fixed in https://github.com/game-icons/icons/commit/c1353b645f6adb2ece365697c8cce522447fa4db
