### ISSUE TITLE
Character icon

### ISSUE THREAD

**Issue by GaryOlsson** [game-icons/icons#716]
In many games you have a character screen and I think a "character" icon should be a great addition to this library.

What I'm loonking for is an anonymous "head with shoulder" icon, like the "king" icon without the crown.
https://game-icons.net/1x1/lorc/king.html

You can see similar icons being used in various RPG
Here is an example in The Elder Scroll MMO
https://us.v-cdn.net/5020507/uploads/FileUpload/97/936347f4c55cc7607213de3a16ba54.png

In WoW UI, they use a picture of your character 3D model but I've seen this kind of icon in many games.

**Comment by Vrixyz** [comment]
For what it's worth, you can use the builtin editor from the game-icons website to remove the crown (foreground -> break apart)

**Comment by Delapouite** [comment]
A neutral character has been added https://game-icons.net/1x1/delapouite/character.html
