### ISSUE TITLE
Stray line on the dynamite icon

### ISSUE THREAD

**Issue by perlDreamer** [game-icons/icons#728]
<img width="515" alt="Screen Shot 2020-08-28 at 8 31 56 PM" src="https://user-images.githubusercontent.com/48078/91627676-c855e180-e96d-11ea-95d9-54dc9b02f0aa.png">

**Comment by Delapouite** [comment]
Thanks. It has been fixed in https://github.com/game-icons/icons/commit/59b9df291b0cd6b5337f597d7f6d4574b599b913
