### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by aloisdg** [game-icons/icons#754]
Hello,

We have a calendar, but I would love to also have a calculator.
Here is a basic submission in html: https://jsfiddle.net/qt187zxv/

I am not well versed in svg, but here is my take: [calculator.zip](https://github.com/game-icons/icons/files/5178019/calculator.zip)

Thank you !

Cheers,

**Comment by Delapouite** [comment]
A calculator has been published https://game-icons.net/1x1/delapouite/calculator.html

**Comment by aloisdg** [comment]
Great! Thank you
