### ISSUE TITLE
Badge: Numbers

### ISSUE THREAD

**Issue by Grovestrider** [game-icons/icons#768]
I would like to see badges with numbers, specifically 1-9.

- [ ] 1

- [ ] 2

- [ ] 3

- [ ] 4

- [ ] 5

- [ ] 6

- [ ] 7

- [ ] 8

- [ ] 9

**Comment by Delapouite** [comment]
The 10 digits have been added.

![image](https://user-images.githubusercontent.com/39315/101278269-8f25dc80-37ba-11eb-8cd1-f4196ad5fb8a.png)
