### ISSUE TITLE
Judge hammer/auction hammer

### ISSUE THREAD

**Issue by joernbjoern** [game-icons/icons#815]
The hammer a judge uses when saying: "order order" 

I liked the hammer that already exists with the name "trample" but maybe it should be in a downswing on to the wooden thing that usually accompanies  the hammer:

Example picture:
https://www.wish.com/product/5a601f95a0386f23214007e2?hide_login_modal=true&from_ad=goog_shopping&_display_country_code=SE&_force_currency_code=SEK&pid=googleadwords_int&c=%7BcampaignId%7D&ad_cid=5a601f95a0386f23214007e2&ad_cc=SE&ad_curr=SEK&ad_price=307.00&campaign_id=9527731155&exclude_install=true&gclid=Cj0KCQjwo-aCBhC-ARIsAAkNQivZLVDFsdcVBniAofc349B_A62-zyhq-x5TTe3igl2BzXyH7ljxXmkaAmouEALw_wcB&share=web

**Comment by Delapouite** [comment]
Hello. Could this one fit: https://game-icons.net/1x1/delapouite/banging-gavel.html ? (I'll add it to the hammer tag, I've just seen that it's missing)

**Comment by joernbjoern** [comment]
Yea it will definitely work for my game! Thank you!
