### ISSUE TITLE
We need an icon for "activating card by turning them on the side" (like tapping things in MTG)

### ISSUE THREAD

**Issue by QuentinBARILLOT** [game-icons/icons#825]
Hi,

We are creating a board game, and we need an icon to understand that a card is used (by turning them 90°, like in magic).

Thanks a lot !!

**Comment by gwelchc** [comment]
Can't you just turn the icon? There are buttons on the web to do that.

![imagen](https://user-images.githubusercontent.com/2284888/119854460-5ec12e80-bf11-11eb-9327-d9a64c61f065.png)

**Comment by andymeneely** [comment]
FYI, maybe these would help? https://github.com/game-icons/icons/pull/833

There isn't an easy way for us to contribute "badges" afaict but the `tap.svg` file is based on existing badges so you can make it manually if you like.

**Comment by QuentinBARILLOT** [comment]
Thx it's perfect !
