### ISSUE TITLE
Suggestion: Philosopher, Schroedinger's Cat, Four Horsemen

### ISSUE THREAD

**Issue by HolgerBecker** [game-icons/icons#832]
Suggestion for three icons:
* Philosopher / Socrates head / Socrates bust
* Schroedinger's cat (dead & alive at the same time) 
* Apocalypse / Four Horsemen of the Apocalypse / Horseman

Thank you!

**Comment by Delapouite** [comment]
A philosopher bust has been added https://game-icons.net/1x1/caro-asercion/philosopher-bust.html

**Comment by Delapouite** [comment]
The schrodingers cat in both version is ready thanks to Caro:
- https://game-icons.net/1x1/caro-asercion/schrodingers-cat-alive.html
- https://game-icons.net/1x1/caro-asercion/schrodingers-cat-dead.html

**Comment by Delapouite** [comment]
The apocalypse horseman was already published: https://game-icons.net/1x1/caro-asercion/cloaked-figure-on-horseback.html
