### ISSUE TITLE
Suggestion: Chemical Weapon Symbol

### ISSUE THREAD

**Issue by maallaard** [game-icons/icons#839]
This is the symbol for chemical weapons, would make a good addition to this database.
![2048px-WMD-chemical svg](https://user-images.githubusercontent.com/64651989/126021220-8fcaf422-a8a3-4518-ac5f-30af5fef78cf.png)

**Comment by Moshk94** [comment]
Hey, is something like this okay?
![image](https://user-images.githubusercontent.com/42604147/134782796-007884aa-78f7-4ac5-a575-099f271d5b56.png)

**Comment by maallaard** [comment]
that’s perfect! couldn’t have done it any better, thanks!
