### ISSUE TITLE
Algolia logo missing

### ISSUE THREAD

**Issue by DreadKnight** [game-icons/icons#857]
Algolia logo is missing from search results dropdown.
![Screenshot_20211206_182032](https://user-images.githubusercontent.com/587487/144882724-4ee23830-84d9-4cd5-ac52-feb81bc49ec7.jpg)

**Comment by Delapouite** [comment]
Thanks for the notice. I guess they did not respect the "Cool URLs don't change". I'll fix that in the next code update.

**Comment by Delapouite** [comment]
It should be good now.
