### ISSUE TITLE
Icon request: Tripod telescope

### ISSUE THREAD

**Issue by bubbyboytoo** [game-icons/icons#878]
Like the existing "Spyglass" icon, but pointed up with a tripod base and eyepiece attached at the top, kind of like this:
![image](https://user-images.githubusercontent.com/12205185/152461524-8736d0b1-2f74-41f1-9df3-067c9149385b.png)

**Comment by Delapouite** [comment]
A telescope has been added : https://game-icons.net/1x1/delapouite/telescope.html
