### ISSUE TITLE
Icon Request: More generic padlock

### ISSUE THREAD

**Issue by iwsundstrom** [game-icons/icons#922]
Current padlock shows a key hole on it: https://game-icons.net/1x1/lorc/padlock.html

Would be great to have a plainer icon with a more solid/square sillhoette. This is an icon I find myself wanting to use a lot as a video game developer to show content remains to be unlocked, but the keyhole one is a bit busy looking for most UI purposes.

As an aside: I use these icons constantly for prototyping. Y'all rule, thank you so much for making them!

**Comment by SG-ALV** [comment]
You could Break Apart the Padlock foreground
