### ISSUE TITLE
Request: Previous button icon

### ISSUE THREAD

**Issue by DanKaplanSES** [game-icons/icons#942]
A [Next button icon](https://game-icons.net/1x1/delapouite/next-button.html) already exists. I would like to request a Back button icon. Flipping the next button icon would probably suffice.

**Comment by Delapouite** [comment]
Hello. Is it the one you're looking for ? https://game-icons.net/1x1/delapouite/previous-button.html

**Comment by DanKaplanSES** [comment]
That absolutely is what I was looking for. I assumed it didn't exist because they are not next to each other in this list and I guess my eyes skimmed over it: https://game-icons.net/tags/gui.html 

Would it make sense to change this issue to be about semantic grouping of the icons in these lists?

**Comment by guiled** [comment]
Can you close your request ?

**Comment by DanKaplanSES** [comment]
Go for it

**Comment by DanKaplanSES** [comment]
@guiled oh, sorry! I misread your reply: I thought you asked, "Can **I** close your request."
