### ISSUE TITLE
Fangs icon issue

### ISSUE THREAD

**Issue by DreadKnight** [game-icons/icons#978]
The fangs icon has some little thing at the bottom that catches strokes:

![Screenshot_20240120_104623](https://github.com/game-icons/icons/assets/587487/fb34466d-7d87-4f47-80d0-5744b7a702b5)

https://game-icons.net/1x1/skoll/fangs.html

**Comment by Delapouite** [comment]
The lonely SVG node in the lower left has been removed. Thanks.
