### ISSUE TITLE
SSL Cert Expired on game-icons.net

### ISSUE THREAD

**Issue by Sean-Eggleston** [game-icons/icons#994]
SSL Cert expired on game-icons.net since Thu, 21 Mar 2024 14:00:24 GMT.

**Comment by Sean-Eggleston** [comment]
Mentioning @Delapouite since he has taken care of several issues of these ( #930, #965, #980 ), and having website SSL down can be considered important.

PS: Serious thanks for having this stuff, guys. This website has been really helpful for my hobbies.

**Comment by Delapouite** [comment]
Thanks for the mention. It's back.
