### ISSUE TITLE
Foundry Manifest Link Broken

### ISSUE THREAD

**Issue by Armandeus66** [game-icons/icons#999]
The game-icons Foundry VTT module cannot be installed or updated through the Foundry interface.

https://github.com/datdamnzotz/icons/blob/master/README-FoundryVTT.md

Error: 404 File Not Found

Error: No module manifest found at https://raw.githubusercontent.com/datdamnzotz/icons/master/module.json

**Comment by Delapouite** [comment]
Hi. I'm afraid you're asking the wrong project. We have nothing to do with Foundry VTT module, which is an extension built by someone else.
